import { expect, test } from '@playwright/test'

test('custom select supports keyboard exploration, cancellation, typeahead, and Tab', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/#/plan')
  const goal = page.getByRole('combobox', { name: 'Goal path', exact: true })
  const original = await goal.getAttribute('data-value')
  await page.locator('label').filter({ has: goal }).click({ position: { x: 8, y: 8 } })
  await expect(goal).toBeFocused()
  await expect(goal).toHaveAttribute('aria-expanded', 'true')
  await page.keyboard.press('Escape')
  await goal.focus()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('End')
  const menu = page.getByRole('listbox', { name: 'Goal path options', exact: true })
  await expect(menu).toBeVisible()
  const bounds = (await menu.boundingBox())!
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(320)
  await page.keyboard.press('Escape')
  await expect(goal).toHaveAttribute('data-value', original!)
  await expect(goal).toBeFocused()
  await goal.pressSequentially('Backend')
  await page.keyboard.press('Enter')
  await expect(goal).toHaveAttribute('data-value', 'backend')
  await page.reload()
  await expect(goal).toHaveAttribute('data-value', 'backend')
  await goal.focus()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Tab')
  await expect(goal).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('spinbutton', { name: 'Minutes per session', exact: true })).toBeFocused()
})

test('custom calendar handles month boundaries, leap days, cancellation, and reload', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-01-31T12:00:00Z'))
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/#/history')
  const date = page.getByRole('button', { name: 'Date', exact: true })
  await date.click()
  const calendar = page.getByRole('dialog')
  await expect(calendar.locator('[data-date="2026-01-31"]')).toBeFocused()
  await page.keyboard.press('PageDown')
  await expect(calendar.locator('[data-date="2026-02-28"]')).toBeFocused()
  await page.keyboard.press('ArrowRight')
  await expect(calendar.locator('[data-date="2026-03-01"]')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(calendar).not.toBeVisible()
  await expect(date).toHaveAttribute('data-value', '')
  await expect(date).toBeFocused()
  await date.click()
  await page.keyboard.press('PageDown')
  await page.keyboard.press('Shift+PageUp')
  await expect(calendar.locator('[data-date="2025-02-28"]')).toBeFocused()
  await page.keyboard.press('Shift+PageUp')
  await expect(calendar.locator('[data-date="2024-02-28"]')).toBeFocused()
  await page.keyboard.press('ArrowRight')
  await expect(calendar.locator('[data-date="2024-02-29"]')).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(date).toHaveAttribute('data-value', '2024-02-29')
  await page.reload()
  await expect(date).toHaveAttribute('data-value', '2024-02-29')
  await date.click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await calendar.getByRole('button', { name: 'Clear date', exact: true }).click()
  await expect(date).toHaveAttribute('data-value', '')
})

test('owned number, search, and choice controls preserve native input behavior', async ({ page }) => {
  await page.goto('/#/plan')
  const minutes = page.getByRole('spinbutton', { name: 'Minutes per session', exact: true })
  const decrease = page.getByRole('button', { name: 'Decrease Minutes per session', exact: true })
  const increase = page.getByRole('button', { name: 'Increase Minutes per session', exact: true })
  await minutes.fill('5')
  await expect(decrease).toBeDisabled()
  await increase.click()
  await expect(minutes).toHaveValue('6')
  await minutes.fill('120')
  await expect(increase).toBeDisabled()
  await decrease.click()
  await expect(minutes).toHaveValue('119')
  await minutes.fill('')
  await expect(minutes).toHaveValue('')
  await page.getByRole('heading', { level: 1 }).click()
  await expect(minutes).toHaveValue('119')
  await page.goto('/#/practice')
  const search = page.getByLabel('Find a rep', { exact: true })
  await search.fill('stock adjustment')
  await expect(page.locator('.rep-list-row')).toHaveCount(1)
  await page.getByRole('button', { name: 'Clear Find a rep', exact: true }).click()
  await expect(search).toHaveValue('')
  await expect(search).toBeFocused()
  expect(await page.locator('.rep-list-row').count()).toBeGreaterThan(1)
  await page.goto('/#/knowledge')
  const choice = page.getByRole('checkbox', { name: 'Bookmarks only', exact: true })
  await choice.focus()
  await page.keyboard.press('Space')
  await expect(choice).toBeChecked()
  expect(await choice.evaluate(element => getComputedStyle(element).appearance)).toBe('none')
})

test('custom popup works inside Profiles and the owned file control preserves failed import recovery', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/#/home')
  const manage = page.getByRole('button', { name: 'Manage profiles' })
  await manage.focus()
  await expect(page.getByRole('tooltip')).toHaveText('Local profile: My learning')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('tooltip')).not.toBeVisible()
  await expect(manage).toBeFocused()
  await manage.click()
  const profiles = page.getByRole('dialog', { name: 'Local profiles' })
  const select = profiles.getByRole('combobox', { name: 'Switch profile', exact: true })
  await select.click()
  await expect(page.getByRole('listbox', { name: 'Switch profile options', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(profiles).toBeVisible()
  await expect(select).toBeFocused()
  await profiles.getByText('Export or import a profile', { exact: true }).click()
  const chooser = page.waitForEvent('filechooser')
  await profiles.getByRole('button', { name: 'Choose file', exact: true }).click()
  await (await chooser).setFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{broken') })
  await expect(profiles.getByRole('status')).not.toHaveText('Importing profile…')
  await expect(profiles.getByRole('status')).not.toBeEmpty()
  await expect(profiles.getByRole('button', { name: 'Close', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Manage profiles' })).toContainText('My learning')
})
