import { paths } from '../../src/path'
import { expect, test } from '@playwright/test'
import { chooseOption, editor, replaceCode, route, saved, solution } from './helpers'

test('real Monaco editing, keyboard checks, and obsolete feedback', async ({ page }) => {
  await page.goto(route)
  await replaceCode(page, solution)
  await page.keyboard.press('ControlOrMeta+Enter')
  await expect(page.getByText('All checks passed', { exact: true })).toBeVisible()
  await replaceCode(page, 'function mostFrequent(numbers: number[]): number | null { return null }')
  await expect(page.getByText('All checks passed', { exact: true })).toHaveCount(0)
  await page.locator('.workspace-toolbar').getByRole('button', { name: /Run checks/ }).click()
  await expect(page.getByText('1 of 6 checks passed', { exact: true })).toBeVisible()
})

test('reload preserves code and planning drafts', async ({ page }) => {
  await page.goto(route)
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.getByLabel('Your plan', { exact: true }).fill('Count values, then resolve ties with the smaller value.')
  await replaceCode(page, solution)
  await saved(page)
  await page.reload()
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await expect(page.getByLabel('Your plan', { exact: true })).toHaveValue('Count values, then resolve ties with the smaller value.')
  await expect(editor(page)).toBeVisible()
  await page.locator('.workspace-toolbar').getByRole('button', { name: /Run checks/ }).click()
  await expect(page.getByText('All checks passed', { exact: true })).toBeVisible()
})

test('profile switching keeps drafts separate', async ({ page }) => {
  await page.goto(route)
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.getByLabel('Your plan', { exact: true }).fill('Original profile plan')
  await replaceCode(page, solution)
  await page.getByRole('button', { name: 'Manage profiles' }).click()
  const dialog = page.getByRole('dialog', { name: 'Local profiles' })
  await dialog.getByText('Create or rename a profile', { exact: true }).click()
  await dialog.getByLabel('Profile name', { exact: true }).fill('Browser test learner')
  await dialog.getByRole('button', { name: 'Create profile', exact: true }).click()
  await expect(dialog.getByRole('status')).toHaveText('Profile created.')
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await page.goto(route)
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await expect(page.getByLabel('Your plan', { exact: true })).toHaveValue('')
  await expect(editor(page)).toBeVisible()
  await expect(page.locator('.view-lines')).toContainText('Write your solution here')
  await page.getByLabel('Your plan', { exact: true }).fill('Separate learner plan')
  await page.getByRole('button', { name: 'Manage profiles' }).click()
  await chooseOption(dialog.getByRole('combobox', { name: 'Switch profile', exact: true }), { label: 'My learning' })
  await expect(dialog.getByRole('combobox', { name: 'Switch profile', exact: true })).toHaveAttribute('data-value', 'default')
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await page.goto(route)
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await expect(page.getByLabel('Your plan', { exact: true })).toHaveValue('Original profile plan')
  await expect(editor(page)).toBeVisible()
  await page.locator('.workspace-toolbar').getByRole('button', { name: /Run checks/ }).click()
  await expect(page.getByText('All checks passed', { exact: true })).toBeVisible()
})

test('narrow workspace preserves planning and supports keyboard exit', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(route)
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.getByLabel('Your plan', { exact: true }).fill('A narrow-screen draft')
  await page.getByRole('button', { name: 'Solve', exact: true }).click()
  await replaceCode(page, solution)
  await page.keyboard.press('Tab')
  await expect(editor(page)).not.toBeFocused()
  await page.locator('.workspace-toolbar').getByRole('button', { name: /Run checks/ }).click()
  await expect(page.getByText('All checks passed', { exact: true })).toBeVisible()
  await saved(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await expect(page.getByLabel('Your plan', { exact: true })).toHaveValue('A narrow-screen draft')
})

test('first-run choice precedes the recommendation and stays editable', async ({ page }) => {
  await page.goto('/#/home')
  const firstRun = page.locator('.first-run-start')
  await expect(firstRun.getByRole('heading', { name: 'Where are you starting?' })).toBeVisible()
  expect(await page.evaluate(() => Boolean(document.querySelector('.first-run-start')!.compareDocumentPosition(document.querySelector('.continue-panel')!) & Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true)
  await firstRun.getByRole('button', { name: /New to coding/ }).click()
  await expect(page.locator('#continue-heading')).toHaveText('Declare a value')
  await expect(firstRun).toHaveCount(0)
  await page.reload()
  await expect(page.locator('#continue-heading')).toHaveText('Declare a value')
  await page.getByText('Change starting point', { exact: true }).click()
  await page.getByRole('button', { name: /Returning to coding/ }).click()
  await expect(page.locator('#continue-heading')).toHaveText('Sum positive numbers')
  await page.locator('.continue-panel').getByRole('button', { name: /Start rep/ }).click()
  await expect(page).toHaveURL(/#\/practice\/sum-positive-numbers$/)
  await page.goBack()
  await expect(page.locator('#continue-heading')).toHaveText('Sum positive numbers')
})

test('failed checks open one case at a time with keyboard access', async ({ page }) => {
  await page.goto(route)
  await page.locator('.workspace-toolbar').getByRole('button', { name: 'Run checks', exact: true }).click()
  await expect(page.getByText('1 of 6 checks passed', { exact: true })).toBeVisible()
  const cases = page.locator('#checks-section .result-list').first().locator('details')
  await expect(cases).toHaveCount(5)
  await expect(page.locator('#checks-section .result-list details[open]')).toHaveCount(1)
  await expect(cases.first()).toHaveAttribute('open', '')
  const second = cases.nth(1).locator('summary')
  await second.focus()
  await second.press('Enter')
  await expect(cases.nth(1)).toHaveAttribute('open', '')
  await expect(cases.first()).not.toHaveAttribute('open', '')
  await expect(page.locator('#checks-section .result-list details[open]')).toHaveCount(1)
  await expect(cases.nth(1)).toContainText('mostFrequent([7])')
  await expect(page.getByRole('list', { name: 'Passed checks' })).toBeVisible()
  await expect(page.locator('.passed-checks li')).toHaveCount(1)
  await expect(page.locator('#code-workspace #checks-section')).toHaveCount(0)
  const workspace = await page.locator('.workspace-layout').boundingBox()
  const checks = await page.locator('#checks-section').boundingBox()
  expect(checks!.y).toBeGreaterThanOrEqual(workspace!.y + workspace!.height)
  expect(checks!.width).toBeCloseTo(workspace!.width, 0)
})

test('practice steps preserve work, explain missing requirements, and record completion', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(route)
  const steps = page.getByRole('navigation', { name: 'Practice steps' })
  await steps.getByRole('button', { name: 'Review', exact: true }).click()
  await expect(page.locator('#review-section')).toBeFocused()
  await page.getByRole('button', { name: 'Write your plan', exact: false }).click()
  await expect(page.locator('#plan-section')).toBeFocused()
  await page.getByLabel('Your plan', { exact: true }).fill('Count occurrences and choose the smaller number when counts tie.')
  await steps.getByRole('button', { name: 'Solve', exact: true }).click()
  await replaceCode(page, solution)
  await page.keyboard.press('ControlOrMeta+Enter')
  await expect(page.getByText('All checks passed', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Explain your solution', exact: false }).click()
  await expect(page.locator('#explain-section')).toBeFocused()
  await page.getByLabel('Your explanation', { exact: true }).fill('I count each value, compare counts, and use the smaller value to break ties. Empty input returns null.')
  await steps.getByRole('button', { name: 'Review', exact: true }).click()
  await chooseOption(page.getByLabel('What was hardest?', { exact: true }), 'edge-cases')
  await chooseOption(page.getByLabel('How confident do you feel?', { exact: true }), 'getting-there')
  await page.getByRole('button', { name: 'Complete rep', exact: false }).click()
  await expect(page.getByText('Completed and saved on this device.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(steps.getByRole('button', { name: 'Review', exact: true })).toHaveAttribute('aria-current', 'step')
  await page.getByRole('button', { name: 'Explain', exact: true }).click()
  await expect(page.getByLabel('Your explanation', { exact: true })).toHaveValue(/I count each value/)
  await steps.getByRole('button', { name: 'Plan', exact: true }).click()
  await expect(page.getByLabel('Your plan', { exact: true })).toHaveValue(/Count occurrences/)
  await page.locator('.site-menu > summary').click()
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: 'Progress', exact: true }).click()
  await expect(page.locator('[aria-label="Practice summary"]')).toContainText('Completed reps1')
  await expect(page.locator('[aria-label="Practice summary"]')).toContainText('Current streak1 days')
  // An unhinted solve before its guided journey is not evidence of independence.
  await expect(page.locator('[aria-label="Skill evidence summary"]')).toContainText('Independent skills0')
  await expect(page.locator('[aria-label="Skill evidence summary"]')).toContainText('Retained skills0')
})

test('lesson section navigation preserves predictions and opens self-review', async ({ page }) => {
  await page.goto('/#/knowledge')
  const sections = page.getByRole('navigation', { name: 'Lesson sections' })
  await sections.getByRole('button', { name: 'Predict', exact: true }).click()
  await expect(sections.getByRole('button', { name: 'Predict', exact: true })).toBeFocused()
  const prediction = page.locator('fieldset.lesson-question').first()
  await prediction.getByRole('radio', { name: '6', exact: true }).check()
  await prediction.getByRole('button', { name: 'Check prediction', exact: true }).click()
  await expect(prediction).toContainText('Correct prediction.')
  await sections.getByRole('button', { name: 'Review', exact: true }).click()
  await expect(page.locator('.lesson-review-details')).toHaveAttribute('open', '')
  await expect(sections.getByRole('button', { name: 'Review', exact: true })).toBeFocused()
  await page.getByLabel('Evidence and what to improve', { exact: true }).fill('I traced the return value; I still need an independent coding attempt.')
  await sections.getByRole('button', { name: 'Read', exact: true }).click()
  await sections.getByRole('button', { name: 'Predict', exact: true }).click()
  await expect(prediction.getByRole('radio', { name: '6', exact: true })).toBeChecked()
  await page.reload()
  await expect(prediction).toContainText('Correct prediction.')
  await sections.getByRole('button', { name: 'Review', exact: true }).click()
  await expect(page.getByLabel('Evidence and what to improve', { exact: true })).toHaveValue(/I traced the return value/)
})

test('narrow path discovery selects a path without horizontal scrolling', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/paths')
  await expect(page.locator('.path-picker')).not.toHaveAttribute('open', '')
  await page.locator('.path-picker > summary').click()
  await page.locator('.path-choices').getByRole('button', { name: /^Backend core/ }).click()
  await expect(page.locator('#path-title')).toHaveText('Backend core')
  await expect(page.locator('#path-title')).toBeFocused()
  await expect(page.locator('.path-picker')).not.toHaveAttribute('open', '')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.reload()
  await expect(page.locator('#path-title')).toHaveText('Backend core')
  await expect(page.locator('.path-picker')).not.toHaveAttribute('open', '')
})

test('local profile progress is readable on narrow screens and links to paths', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/progress')
  await expect(page.getByRole('heading', { name: 'My learning', exact: true })).toBeVisible()
  await expect(page.getByRole('definition').filter({ hasText: /^0 days$/ })).toHaveCount(2)
  await expect(page.getByRole('heading', { name: 'Path completion badges' })).toBeVisible()
  await expect(page.locator('.profile-badge-list li')).toHaveCount(paths.length)
  await expect(page.locator('.profile-summary')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.locator('.profile-badge-list').getByRole('button', { name: 'Explore path' }).first().focus()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/#\/paths/)
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'My learning', exact: true })).toBeVisible()
})

test('checks use a full-width light sheet below the retained workspace', async ({ page }) => {
  await page.goto(route)
  await replaceCode(page, solution)
  await page.keyboard.press('ControlOrMeta+Enter')
  const checks = page.locator('#checks-section')
  await expect(page.getByText('All checks passed', { exact: true })).toBeVisible()
  await expect(checks.locator('.passed-checks li')).toHaveCount(6)
  for (const width of [1280, 320]) {
    await page.setViewportSize({ width, height: 900 })
    const workspaceBox = await page.locator('.workspace-layout').boundingBox()
    const checksBox = await checks.boundingBox()
    expect(checksBox!.y).toBeGreaterThanOrEqual(workspaceBox!.y + workspaceBox!.height)
    expect(checksBox!.width).toBeCloseTo(workspaceBox!.width, 0)
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(await checks.evaluate(element => getComputedStyle(element).backgroundColor)).toBe('rgb(232, 243, 226)')
  }
  const toggle = checks.getByRole('button', { name: /^Checks/ })
  await toggle.focus()
  await toggle.press('Enter')
  await expect(page.locator('#check-details')).toBeHidden()
  await toggle.press('Enter')
  await expect(page.getByRole('list', { name: 'Passed checks' })).toBeVisible()
  await expect.poll(() => page.evaluate(() => Object.entries(localStorage).filter(([key]) => key.includes('most-frequent-number')).map(([, value]) => JSON.parse(value).code))).toContain(solution)
})

test('desktop desk stays fixed while task and checks scroll', async ({ page }) => {
  for (const height of [900, 600]) {
    await page.setViewportSize({ width: 1280, height })
    await page.goto(route)
    await expect(editor(page)).toBeVisible()
    await page.getByRole('button', { name: /^Reveal hint/ }).click()
    const task = page.locator('.task-column')
    await task.hover()
    await page.mouse.wheel(0, 1000)
    await expect.poll(() => task.evaluate(node => node.scrollTop)).toBeGreaterThan(0)
    await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
    await replaceCode(page, solution)
    await page.locator('.workspace-toolbar').getByRole('button', { name: /Run checks/ }).click()
    await expect(page.getByText('All checks passed', { exact: true })).toBeVisible()
    const run = page.locator('.workspace-toolbar').getByRole('button', { name: /Run checks/ })
    const bounds = await run.boundingBox()
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(height)
    expect(await page.locator('.code-column').evaluate(node => node.scrollHeight - node.clientHeight)).toBeLessThanOrEqual(1)
    expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(height)
    await page.locator('#check-details').hover()
    await page.mouse.wheel(0, 1000)
    await expect.poll(() => page.locator('#check-details').evaluate(node => node.scrollTop)).toBeGreaterThan(0)
    await page.getByRole('button', { name: /^Checks/ }).click()
    await expect(page.locator('#check-details')).toBeHidden()
    await expect(editor(page)).toBeVisible()
    await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  }
})
