import { expect, test } from '@playwright/test'
import { expectChecksFinished, chooseOption, chooseSegment, editor, replaceCode, route, saved, solution } from './helpers'

test('real Monaco editing, keyboard checks, and obsolete feedback', async ({ page }) => {
  await page.goto(route)
  await replaceCode(page, solution)
  await page.keyboard.press('ControlOrMeta+Enter')
  await expectChecksFinished(page.getByText('All checks passed', { exact: true }))
  await replaceCode(page, 'function mostFrequent(numbers: number[]): number | null { return null }')
  await expect(page.getByText('All checks passed', { exact: true })).toHaveCount(0)
  await page.locator('.workspace-toolbar').getByRole('button', { name: /Run checks/ }).click()
  await expectChecksFinished(page.getByText('1 of 6 checks passed', { exact: true }))
})

test('reload preserves code and planning drafts', async ({ page }) => {
  await page.goto(route)
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.getByLabel('Your plan', { exact: true }).fill('Count values, then resolve ties with the smaller value.')
  await replaceCode(page, solution)
  await saved(page)
  await page.reload()
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await expect(page.getByLabel('Your plan', { exact: true })).toHaveValue('Count values, then resolve ties with the smaller value.')
  await expect(editor(page)).toBeVisible()
  await page.locator('.workspace-toolbar').getByRole('button', { name: /Run checks/ }).click()
  await expectChecksFinished(page.getByText('All checks passed', { exact: true }))
})

test('profile switching keeps drafts separate', async ({ page }) => {
  await page.goto(route)
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.getByLabel('Your plan', { exact: true }).fill('Original profile plan')
  await replaceCode(page, solution)
  await page.getByRole('button', { name: 'Manage profiles' }).click()
  const dialog = page.getByRole('dialog', { name: 'Local profiles' })
  await dialog.getByText('Create or rename a profile', { exact: true }).click()
  await dialog.getByLabel('Profile name', { exact: true }).fill('Browser test learner')
  await dialog.getByRole('button', { name: 'Create profile', exact: true }).click()
  await expect(dialog.getByRole('status')).toHaveText('Profile created.')
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await page.goto(route)
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await expect(page.getByLabel('Your plan', { exact: true })).toHaveValue('')
  await expect(editor(page)).toBeVisible()
  await expect(page.locator('.view-lines')).toContainText('Write your solution here')
  await page.getByLabel('Your plan', { exact: true }).fill('Separate learner plan')
  await page.getByRole('button', { name: 'Manage profiles' }).click()
  await chooseOption(dialog.getByRole('combobox', { name: 'Switch profile', exact: true }), { label: 'My learning' })
  await expect(dialog.getByRole('combobox', { name: 'Switch profile', exact: true })).toHaveAttribute('data-value', 'default')
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await page.goto(route)
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await expect(page.getByLabel('Your plan', { exact: true })).toHaveValue('Original profile plan')
  await expect(editor(page)).toBeVisible()
  await page.locator('.workspace-toolbar').getByRole('button', { name: /Run checks/ }).click()
  await expectChecksFinished(page.getByText('All checks passed', { exact: true }))
})

test('narrow workspace preserves planning and supports keyboard exit', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(route)
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.getByLabel('Your plan', { exact: true }).fill('A narrow-screen draft')
  await page.getByRole('button', { name: 'Solve', exact: true }).click()
  await replaceCode(page, solution)
  await page.keyboard.press('Tab')
  await expect(editor(page)).not.toBeFocused()
  await page.locator('.workspace-toolbar').getByRole('button', { name: /Run checks/ }).click()
  await expectChecksFinished(page.getByText('All checks passed', { exact: true }))
  await saved(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await expect(page.getByLabel('Your plan', { exact: true })).toHaveValue('A narrow-screen draft')
})

test('first-run recommendation leads and the starting point stays editable', async ({ page }) => {
  await page.goto('/#/home')
  const starting = page.locator('.starting-point-settings')
  await expect(starting.locator('summary')).toContainText('Starting as: Not chosen yet · Choose')
  expect(await page.evaluate(() => Boolean(document.querySelector('.continue-panel')!.compareDocumentPosition(document.querySelector('.starting-point-settings')!) & Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true)
  await starting.locator('summary').click()
  await starting.getByRole('button', { name: /New to coding/ }).click()
  await expect(page.locator('#continue-heading')).toHaveText('Declare a value')
  await expect(starting.locator('summary')).toContainText('Starting as: New to coding · Change')
  await page.reload()
  await expect(page.locator('#continue-heading')).toHaveText('Declare a value')
  await starting.locator('summary').click()
  await starting.getByRole('button', { name: /Returning to coding/ }).click()
  await expect(page.locator('#continue-heading')).toHaveText('Sum positive numbers')
  await page.locator('.continue-panel').getByRole('button', { name: /Start rep/ }).click()
  await expect(page).toHaveURL(/#\/practice\/sum-positive-numbers$/)
  await page.goBack()
  await expect(page.locator('#continue-heading')).toHaveText('Sum positive numbers')
})

test('Complete stays a normal button before a difficulty choice and names the one thing still needed', async ({ page }) => {
  await page.goto(route)
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.getByLabel('Your plan', { exact: true }).fill('Count occurrences and choose the smaller number when counts tie.')
  await replaceCode(page, solution)
  await page.locator('.workspace-toolbar').getByRole('button', { name: /Run checks/ }).click()
  await expectChecksFinished(page.getByText('All checks passed', { exact: true }))
  // Once checks pass, the only route to the explanation is the checks drawer, not a second footer link.
  await expect(page.locator('.workspace-toolbar').getByRole('button', { name: 'Explain solution', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Explain', exact: true }).click()
  await page.getByLabel('Your explanation', { exact: true }).fill('I count each value, compare counts, and use the smaller value to break ties. Empty input returns null.')
  await page.getByRole('button', { name: 'Review', exact: true }).click()
  const complete = page.getByRole('button', { name: 'Complete rep', exact: true })
  // Complete is not greyed out; the one missing item is named in the note and the checklist, with the same words.
  await expect(complete).toBeEnabled()
  await expect(page.locator('.finish-note')).toHaveText('Still needed: a difficulty choice.')
  await expect(page.locator('.completion-checklist')).toContainText('Still needed: a difficulty choice')
  await complete.click()
  // Pressing Complete with the choice missing moves focus to the difficulty control, which describes what is needed.
  const difficulty = page.locator('#difficulty-choice button').first()
  await expect(difficulty).toBeFocused()
  await expect(difficulty).toHaveAccessibleDescription('Still needed: a difficulty choice.')
  await expect(page.getByText('Your attempt is saved in the Journal.', { exact: true })).toHaveCount(0)
  await chooseSegment(page, 'What was hardest?', 'Nothing in particular')
  await expect(page.locator('.finish-note')).toHaveCount(0)
  await complete.click()
  await expect(page.getByText('Your attempt is saved in the Journal.', { exact: true })).toBeVisible()
})

test('failed checks open one case at a time with keyboard access', async ({ page }) => {
  await page.goto(route)
  await page.locator('.workspace-toolbar').getByRole('button', { name: 'Run checks', exact: true }).click()
  await expectChecksFinished(page.getByText('1 of 6 checks passed', { exact: true }))
  const cases = page.locator('#checks-section .result-list').first().locator('details')
  await expect(cases).toHaveCount(5)
  await expect(page.locator('#checks-section .result-list details[open]')).toHaveCount(1)
  await expect(cases.first()).toHaveAttribute('open', '')
  const second = cases.nth(1).locator('summary')
  await second.focus()
  await second.press('Enter')
  await expect(cases.nth(1)).toHaveAttribute('open', '')
  await expect(cases.first()).not.toHaveAttribute('open', '')
  await expect(page.locator('#checks-section .result-list details[open]')).toHaveCount(1)
  await expect(cases.nth(1)).toContainText('mostFrequent([7])')
  await expect(page.getByRole('list', { name: 'Passed checks' })).toBeVisible()
  await expect(page.locator('.passed-checks li')).toHaveCount(1)
  await expect(page.locator('#code-workspace #checks-section')).toHaveCount(1)
  const desk = await page.locator('#code-workspace').boundingBox()
  const checks = await page.locator('#checks-section').boundingBox()
  const toolbar = await page.locator('.workspace-toolbar').boundingBox()
  expect(checks!.y).toBeGreaterThanOrEqual(desk!.y)
  expect(checks!.y + checks!.height).toBeLessThanOrEqual(toolbar!.y + 1)
  expect(checks!.height).toBeLessThanOrEqual(desk!.height / 2 + 1)
  expect(checks!.width).toBeLessThanOrEqual(desk!.width)
})

test('practice steps preserve work, explain missing requirements, and record completion', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(route)
  const steps = page.getByRole('navigation', { name: 'Practice steps' })
  await steps.getByRole('button', { name: 'Review', exact: true }).click()
  await expect(page.locator('#review-section')).toBeFocused()
  await page.getByRole('button', { name: 'Continue: plan', exact: false }).click()
  await expect(page.locator('#plan-section')).toBeFocused()
  await page.getByLabel('Your plan', { exact: true }).fill('Count occurrences and choose the smaller number when counts tie.')
  await steps.getByRole('button', { name: 'Solve', exact: true }).click()
  await replaceCode(page, solution)
  await page.keyboard.press('ControlOrMeta+Enter')
  await expectChecksFinished(page.getByText('All checks passed', { exact: true }))
  await page.getByRole('button', { name: 'Explain your solution', exact: false }).click()
  await expect(page.locator('#explain-section')).toBeFocused()
  await page.getByLabel('Your explanation', { exact: true }).fill('I count each value, compare counts, and use the smaller value to break ties. Empty input returns null.')
  await steps.getByRole('button', { name: 'Review', exact: true }).click()
  await chooseSegment(page, 'What was hardest?', 'Handling edge cases')
  await chooseSegment(page, 'How confident do you feel?', 'Getting there')
  await page.getByRole('button', { name: 'Complete rep', exact: false }).click()
  await expect(page.getByText('Your attempt is saved in the Journal.', { exact: true })).toBeVisible()
  await expect(page.getByRole('status').filter({ hasText: 'Rep completed' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Complete rep' })).toHaveCount(0)
  await expect(page.locator('#checks-section').getByRole('button', { name: 'Explain your solution' })).toHaveCount(0)
  await expect(page.locator('.workspace-save-status')).toHaveText('Saved in browser')
  await expect(page.getByRole('button', { name: /^Next rep: / })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Done for today', exact: true })).toBeVisible()
  await page.reload()
  await expect(steps.getByRole('button', { name: 'Review', exact: true })).toHaveAttribute('aria-current', 'step')
  await page.getByRole('button', { name: 'Explain', exact: true }).click()
  await expect(page.getByLabel('Your explanation', { exact: true })).toHaveValue(/I count each value/)
  await steps.getByRole('button', { name: 'Plan', exact: true }).click()
  await expect(page.getByLabel('Your plan', { exact: true })).toHaveValue(/Count occurrences/)
  await page.locator('.site-menu > summary').click()
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: 'Progress', exact: true }).click()
  await expect(page.locator('[aria-label="Practice summary"] > div').filter({ has: page.locator('dt', { hasText: 'Completed reps' }) }).locator('dd')).toHaveText('1')
  await expect(page.locator('[aria-label="Practice summary"] > div').filter({ has: page.locator('dt', { hasText: 'Current streak' }) }).locator('dd')).toHaveText('1 day')
  await expect(page.locator('.badge-progress').first()).toHaveText('1 of 1 rep')
  // An unhinted solve before its guided journey is not evidence of independence.
  await expect(page.locator('[aria-label="Practice summary"] > div').filter({ has: page.locator('dt', { hasText: 'Independent skills' }) }).locator('dd')).toHaveText('0')
  await expect(page.locator('[aria-label="Practice summary"] > div').filter({ has: page.locator('dt', { hasText: 'Retained skills' }) }).locator('dd')).toHaveText('0')
})

test('lesson section navigation preserves predictions and opens self-review', async ({ page }) => {
  await page.goto('/#/knowledge')
  const sections = page.getByRole('navigation', { name: 'Lesson sections' })
  await sections.getByRole('button', { name: 'Predict', exact: true }).click()
  await expect(sections.getByRole('button', { name: 'Predict', exact: true })).toBeFocused()
  const prediction = page.locator('fieldset.lesson-question').first()
  await prediction.getByRole('radio', { name: '6', exact: true }).check()
  await prediction.getByRole('button', { name: 'Check prediction', exact: true }).click()
  await expect(prediction).toContainText('Correct prediction.')
  await sections.getByRole('button', { name: 'Review', exact: true }).click()
  await expect(page.locator('.lesson-review-details')).toHaveAttribute('open', '')
  await expect(sections.getByRole('button', { name: 'Review', exact: true })).toBeFocused()
  await page.getByLabel('Evidence and what to improve', { exact: true }).fill('I traced the return value; I still need an independent coding attempt.')
  await sections.getByRole('button', { name: 'Read', exact: true }).click()
  await sections.getByRole('button', { name: 'Predict', exact: true }).click()
  await expect(prediction.getByRole('radio', { name: '6', exact: true })).toBeChecked()
  await page.reload()
  await expect(prediction).toContainText('Correct prediction.')
  await sections.getByRole('button', { name: 'Review', exact: true }).click()
  await expect(page.getByLabel('Evidence and what to improve', { exact: true })).toHaveValue(/I traced the return value/)
})

test('narrow path discovery selects a path without horizontal scrolling', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/paths')
  await expect(page.locator('.path-picker')).not.toHaveAttribute('open', '')
  await page.locator('.path-picker > summary').click()
  await page.locator('.path-choices').getByRole('button', { name: /^Backend/ }).click()
  await expect(page.locator('#path-title')).toHaveText('Backend')
  await expect(page.locator('#path-title')).toBeFocused()
  await expect(page.locator('.path-picker')).not.toHaveAttribute('open', '')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.reload()
  await expect(page.locator('#path-title')).toHaveText('Backend')
  await expect(page.locator('.path-picker')).not.toHaveAttribute('open', '')
})

test('local profile progress is readable on narrow screens and links to the skill map', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/progress')
  await expect(page.getByRole('heading', { name: 'My learning', exact: true })).toBeVisible()
  await expect(page.getByRole('definition').filter({ hasText: /^0 days$/ })).toHaveCount(2)
  await expect(page.getByRole('heading', { name: 'Badges earned' })).toBeVisible()
  await expect(page.getByText(/Upcoming badges/)).toHaveCount(0)
  await expect(page.locator('.profile-summary')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Skill map' }).focus()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/#\/skillmap/)
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'My learning', exact: true })).toBeVisible()
})

test('checks open as a bounded drawer inside the coding desk above the run toolbar', async ({ page }) => {
  await page.goto(route)
  await replaceCode(page, solution)
  await page.keyboard.press('ControlOrMeta+Enter')
  const checks = page.locator('#checks-section')
  await expectChecksFinished(page.getByText('All checks passed', { exact: true }))
  await expect(checks.locator('.passed-checks li')).toHaveCount(6)
  for (const width of [1280, 320]) {
    await page.setViewportSize({ width, height: 900 })
    const desk = await page.locator('#code-workspace').boundingBox()
    const checksBox = await checks.boundingBox()
    const editorBox = await page.locator('#solution-section').boundingBox()
    const toolbar = await page.locator('.workspace-toolbar').boundingBox()
    await expect(page.locator('#code-workspace #checks-section')).toHaveCount(1)
    expect(checksBox!.y).toBeGreaterThanOrEqual(editorBox!.y + editorBox!.height - 1)
    // The toolbar is sticky on narrow screens, so compare flow order there instead of positions.
    if (width > 900) expect(checksBox!.y + checksBox!.height).toBeLessThanOrEqual(toolbar!.y + 1)
    else expect(await checks.evaluate(element => Boolean(element.compareDocumentPosition(document.querySelector('.workspace-toolbar')!) & Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true)
    expect(checksBox!.x).toBeGreaterThanOrEqual(desk!.x)
    expect(checksBox!.x + checksBox!.width).toBeLessThanOrEqual(desk!.x + desk!.width + 1)
    // Desktop bounds the drawer; narrow screens let it follow the editor in the Solve pane.
    if (width > 900) expect(checksBox!.height).toBeLessThanOrEqual(desk!.height / 2 + 1)
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    // The drawer is part of the dark desk: the passed surface is the desk's success tone.
    expect(await checks.evaluate(element => getComputedStyle(element).backgroundColor)).toBe('rgb(32, 60, 53)')
  }
  const toggle = checks.getByRole('button', { name: /^Checks/ })
  await toggle.focus()
  await toggle.press('Enter')
  await expect(page.locator('#check-details')).toBeHidden()
  await toggle.press('Enter')
  await expect(page.getByRole('list', { name: 'Passed checks' })).toBeVisible()
  await expect.poll(() => page.evaluate(() => Object.entries(localStorage).filter(([key]) => key.includes('most-frequent-number')).map(([, value]) => JSON.parse(value).code))).toContain(solution)
})

test('compact header shows the editor, first step, and an in-desk drawer without scrolling', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto(route)
  await expect(editor(page)).toBeVisible()
  const first = page.getByRole('navigation', { name: 'Practice steps' }).getByRole('button', { name: 'Understand', exact: true })
  await expect(first).toBeInViewport({ ratio: 1 })
  await expect(page.getByRole('heading', { level: 1, name: 'Find the most frequent number' })).toBeInViewport({ ratio: 1 })
  const header = await page.locator('.workspace-header').boundingBox()
  expect(header!.y + header!.height).toBeLessThan(130)
  const editorBox = await page.locator('#solution-section').boundingBox()
  expect(editorBox!.y).toBeLessThan(200)
  expect(editorBox!.height).toBeGreaterThan(400)
  await page.getByRole('button', { name: 'Run checks', exact: true }).click()
  const checks = page.locator('#code-workspace #checks-section')
  await expect(checks.getByRole('button', { name: /^Checks/ })).toHaveAttribute('aria-expanded', 'true')
  await expectChecksFinished(checks.getByText('1 of 6 checks passed', { exact: true }))
  await expect(checks).toBeInViewport({ ratio: 1 })
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight)).toBe(true)
  expect(await page.evaluate(() => scrollY)).toBe(0)
})

test('desktop desk stays fixed while task and checks scroll', async ({ page }) => {
  for (const height of [900, 600]) {
    await page.setViewportSize({ width: 1280, height })
    await page.goto(route)
    await expect(editor(page)).toBeVisible()
    // Reveal every remaining hint so the brief overflows the roomier compact desk.
    const nextHint = page.getByRole('button', { name: /^Reveal hint/ })
    while (await nextHint.count()) await nextHint.click()
    const task = page.locator('.task-column')
    await task.hover()
    await page.mouse.wheel(0, 1000)
    await expect.poll(() => task.evaluate(node => node.scrollTop)).toBeGreaterThan(0)
    await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
    await replaceCode(page, solution)
    await page.locator('.workspace-toolbar').getByRole('button', { name: /Run checks/ }).click()
    await expectChecksFinished(page.getByText('All checks passed', { exact: true }))
    const run = page.locator('.workspace-toolbar').getByRole('button', { name: /Run checks/ })
    const bounds = await run.boundingBox()
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(height)
    expect(await page.locator('.code-column').evaluate(node => node.scrollHeight - node.clientHeight)).toBeLessThanOrEqual(1)
    expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(height)
    await page.locator('#check-details').hover()
    await page.mouse.wheel(0, 1000)
    await expect.poll(() => page.locator('#check-details').evaluate(node => node.scrollTop)).toBeGreaterThan(0)
    await page.getByRole('button', { name: /^Checks/ }).click()
    await expect(page.locator('#check-details')).toBeHidden()
    await expect(editor(page)).toBeVisible()
    await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  }
})
