import { expect, test } from '@playwright/test'
import { chooseOption, editor, replaceCode, route, solution } from './helpers'

test('focused writing steps preserve the real editor and hide unrelated forms', async ({ page }) => {
  await page.goto(route)
  await expect(editor(page)).toBeVisible()
  for (const menu of ['.site-menu', '.workspace-options']) {
    await page.locator(`${menu} > summary`).focus()
    await page.keyboard.press('Enter')
    await expect(page.locator(menu)).toHaveAttribute('open', '')
    await page.keyboard.press('Tab')
    await page.keyboard.press('Escape')
    await expect(page.locator(menu)).not.toHaveAttribute('open', '')
    await expect(page.locator(`${menu} > summary`)).toBeFocused()
  }
  await expect(page.getByLabel('Your plan', { exact: true })).not.toBeVisible()
  await expect(page.getByLabel('Your explanation', { exact: true })).not.toBeVisible()
  await expect(page.getByLabel('What was hardest?', { exact: true })).not.toBeVisible()
  await replaceCode(page, solution)
  await editor(page).press('ArrowDown')
  const cursor = await page.locator('.monaco-editor .cursor').first().evaluate(element => ({ top: (element as HTMLElement).style.top, left: (element as HTMLElement).style.left }))
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.getByLabel('Your plan', { exact: true }).fill('Count values and use the smaller value to resolve a tie.')
  await expect(editor(page)).toBeVisible()
  await page.getByRole('button', { name: 'Explain', exact: true }).click()
  await page.getByLabel('Your explanation', { exact: true }).fill('Counts identify the most frequent value.')
  await expect(page.getByLabel('Your plan', { exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: 'Solve', exact: true }).click()
  await expect(page.getByLabel('Your explanation', { exact: true })).not.toBeVisible()
  expect(await page.locator('.monaco-editor .cursor').first().evaluate(element => ({ top: (element as HTMLElement).style.top, left: (element as HTMLElement).style.left }))).toEqual(cursor)
  await page.getByRole('button', { name: 'Run checks', exact: true }).click()
  await expect(page.getByText('All checks passed', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^Checks/ }).click()
  await expect(page.getByText('All checks passed', { exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: /^Checks/ }).click()
  await expect(page.getByText('All checks passed', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await expect(page.getByLabel('Your plan', { exact: true })).toHaveValue(/Count values/)
})

test('grouped navigation supports direct links, refresh, and Back and Forward', async ({ page }) => {
  await page.goto('/#/home')
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  // Screen navigation focuses the heading; Shift+Tab from the brand reaches the skip link.
  await page.getByRole('button', { name: 'Code Reps home', exact: true }).focus()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('link', { name: 'Skip to content' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { level: 1 })).toBeFocused()
  const main = page.getByRole('navigation', { name: 'Main navigation' })
  await expect(main.getByRole('button')).toHaveText(['Home', 'Practice', 'Learn', 'Progress'])
  await main.getByRole('button', { name: 'Practice', exact: true }).click()
  await page.getByRole('navigation', { name: 'Practice pages' }).getByRole('button', { name: 'Projects', exact: true }).click()
  await expect(page).toHaveURL(/#\/projects$/)
  await page.reload()
  await expect(main.getByRole('button', { name: 'Practice', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.getByRole('navigation', { name: 'Practice pages' }).getByRole('button', { name: 'Interview', exact: true }).click()
  await chooseOption(page.getByLabel('Interview focus', { exact: true }), 'interview-backend')
  await page.goBack()
  await expect(page).toHaveURL(/#\/projects$/)
  await page.goForward()
  await expect(page.getByLabel('Interview focus', { exact: true })).toHaveAttribute('data-value', 'interview-backend')
  await main.getByRole('button', { name: 'Learn', exact: true }).click()
  await page.getByRole('navigation', { name: 'Learning pages' }).getByRole('button', { name: 'Notebook', exact: true }).click()
  await expect(page).toHaveURL(/#\/notebook$/)
  await page.reload()
  await expect(main.getByRole('button', { name: 'Learn', exact: true })).toHaveAttribute('aria-current', 'page')
  await main.getByRole('button', { name: 'Progress', exact: true }).click()
  await page.getByRole('navigation', { name: 'Progress pages' }).getByRole('button', { name: 'Self-assessment', exact: true }).click()
  await expect(page).toHaveURL(/#\/assessment$/)
  await expect(page.getByRole('button', { name: 'Start assessment', exact: true })).toBeVisible()
})

test('all product pages fit a narrow screen and lessons open without the topic list', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  for (const view of ['home', 'practice', 'paths', 'knowledge', 'notebook', 'plan', 'projects', 'interview', 'assessment', 'progress', 'history', 'learn']) {
    await page.goto(`/#/${view}`)
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), view).toBe(true)
    await expect(page.getByText('Saved in browser', { exact: true })).toBeVisible()
  }
  await page.goto('/#/knowledge')
  await expect(page.getByLabel('Search knowledge', { exact: true })).not.toBeVisible()
  await page.locator('.knowledge-browser > summary').click()
  await page.getByLabel('Search knowledge', { exact: true }).fill('Cancellation and race conditions')
  await page.getByRole('button', { name: 'Cancellation and race conditions', exact: true }).click()
  await expect(page.getByLabel('Search knowledge', { exact: true })).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'Cancellation and race conditions', exact: true })).toBeVisible()
})
