import { expect, test } from '@playwright/test'
import { replaceCode } from './helpers'

test('post-solve trace supports scoped keyboard navigation and narrow review', async ({ page }) => {
  await page.goto('/#/practice/algo-sorted-pair')
  await page.getByRole('button', { name: 'Explain', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Step trace' })).toHaveCount(0)
  await replaceCode(page, 'function hasSortedPair(numbers: number[], target: number): boolean { let left = 0, right = numbers.length - 1; while (left < right) { const sum = numbers[left] + numbers[right]; if (sum === target) return true; if (sum < target) left++; else right-- } return false }', 'algo-sorted-pair')
  await page.getByRole('button', { name: 'Run checks', exact: true }).click()
  await expect(page.getByText('All checks passed', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Explain', exact: true }).click()
  await page.getByText('Compare your plan and explanation', { exact: true }).click()
  const viewer = page.getByRole('region', { name: 'Step trace' })
  await viewer.focus()
  await expect(viewer.getByRole('button', { name: 'Prev', exact: true })).toBeDisabled()
  await viewer.press('ArrowRight')
  await expect(viewer.locator('.trace-note')).toContainText('Step 2 of 7')
  await expect(viewer.locator('.trace-vars')).toContainText('changed')
  await viewer.press('ArrowLeft')
  await expect(viewer.locator('.trace-note')).toContainText('Step 1 of 7')
  await page.getByRole('button', { name: 'Explain', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(viewer.locator('.trace-note')).toContainText('Step 1 of 7')
  await viewer.getByRole('button', { name: 'Go to step 7', exact: true }).click()
  await expect(viewer.getByRole('button', { name: 'Next', exact: true })).toBeDisabled()
  await viewer.press('ArrowRight')
  await expect(viewer.locator('.trace-note')).toContainText('Step 7 of 7')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 320, height: 844 })
  await expect(viewer).toBeVisible()
  expect(await viewer.locator('.trace-panes').evaluate(node => getComputedStyle(node).gridTemplateColumns.split(' ').length)).toBe(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
