import { test, expect } from '@playwright/test'
import { chooseOption, expectChecksFinished, replaceCode, saved } from './helpers'

const greeting = 'function makeGreeting(name: string): string { const greeting = "Hello, "; let message = greeting + name; return message }'
const help = (page: import('@playwright/test').Page) => page.getByRole('complementary', { name: 'First rep walkthrough' })

test('walkthrough skip, replay, reload and Back preserve the real draft', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/home')
  await page.getByRole('button', { name: 'Try first rep walkthrough', exact: true }).click()
  await expect(page).toHaveURL(/#\/practice\/declare-variables$/)
  await help(page).getByRole('button', { name: 'Walkthrough: plan next' }).click()
  await page.getByLabel('Your plan', { exact: true }).fill('My saved walkthrough plan')
  await help(page).getByRole('button', { name: 'Walkthrough: solve next' }).click()
  await replaceCode(page, greeting, 'declare-variables')
  await saved(page)
  await page.reload()
  await expect(help(page)).toContainText('3 of 5')
  await help(page).getByRole('button', { name: 'Skip walkthrough' }).click()
  await expect(help(page)).toHaveCount(0)
  await page.reload()
  await expect(help(page)).toHaveCount(0)
  await page.goBack()
  await expect(page).toHaveURL(/#\/home$/)
  await page.getByText('How a rep works', { exact: true }).click()
  await page.getByRole('button', { name: 'Replay walkthrough' }).click()
  await expect(help(page)).toContainText('1 of 5')
  await help(page).getByRole('button', { name: 'Walkthrough: plan next' }).click()
  await expect(page.getByLabel('Your plan', { exact: true })).toHaveValue('My saved walkthrough plan')
  await help(page).getByRole('button', { name: 'Walkthrough: solve next' }).click()
  await page.getByRole('button', { name: 'Run checks', exact: true }).click()
  await expectChecksFinished(page.getByText('All checks passed', { exact: true }))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('walkthrough uses real checks, hints, writing and completion without granting mastery', async ({ page }) => {
  await page.goto('/#/home')
  await page.getByRole('button', { name: 'Try first rep walkthrough' }).click()
  await help(page).getByRole('button', { name: 'Walkthrough: plan next' }).click()
  await page.getByLabel('Your plan', { exact: true }).fill('Combine the fixed greeting with the supplied name.')
  await help(page).getByRole('button', { name: 'Walkthrough: solve next' }).click()
  await page.getByRole('button', { name: 'Run checks', exact: true }).click()
  await expectChecksFinished(page.getByText('0 of 3 checks passed', { exact: true }))
  await page.getByRole('button', { name: 'Understand', exact: true }).click()
  await page.getByRole('button', { name: 'Reveal hint 1', exact: true }).click()
  await page.getByRole('button', { name: 'Solve', exact: true }).click()
  await replaceCode(page, greeting, 'declare-variables')
  await page.getByRole('button', { name: 'Run checks', exact: true }).click()
  await expectChecksFinished(page.getByText('All checks passed', { exact: true }))
  await help(page).getByRole('button', { name: 'Walkthrough: explain next' }).click()
  await page.getByLabel('Your explanation', { exact: true }).fill('I combine the greeting and name, then return the message. I reviewed const and let myself.')
  await help(page).getByRole('button', { name: 'Walkthrough: review next' }).click()
  await expect(page.getByRole('button', { name: 'Complete rep', exact: true })).toBeDisabled()
  await chooseOption(page.getByLabel('What was hardest?', { exact: true }), 'typescript')
  await chooseOption(page.getByLabel('How confident do you feel?', { exact: true }), 'getting-there')
  await page.getByRole('button', { name: 'Complete rep', exact: true }).click()
  await expect(help(page)).toContainText('Your attempt is saved')
  const finish = help(page).getByRole('button', { name: 'Finish walkthrough' })
  await finish.focus()
  await finish.press('Enter')
  await expect(page.locator('#review-section')).toBeFocused()
  await expect(page.getByText('Attempt recorded in History.', { exact: true })).toBeVisible()
  await expect(page.locator('.workspace-save-status')).toHaveText('Saved in browser')
  const work = await page.evaluate(() => Object.entries(localStorage).filter(([key]) => key.includes('declare-variables')))
  await page.goto('/#/home')
  await expect(page.getByRole('button', { name: 'Replay walkthrough' })).not.toBeVisible()
  await page.getByText('How a rep works', { exact: true }).click()
  await expect(page.locator('.info-note[open]')).toContainText('Opening a rep records no session')
  await page.getByRole('button', { name: 'Replay walkthrough' }).click()
  for (const [number, action] of [[1, 'plan'], [2, 'solve'], [3, 'explain'], [4, 'review']] as const) {
    await expect(help(page)).toContainText(`${number} of 5`)
    await help(page).getByRole('button', { name: `Walkthrough: ${action} next` }).click()
  }
  await expect(help(page)).toContainText('Your attempt is saved')
  expect(await page.evaluate(() => Object.entries(localStorage).filter(([key]) => key.includes('declare-variables')))).toEqual(work)
  await page.goto('/#/progress')
  await expect(page.locator('[aria-label="Practice summary"]')).toContainText('Independent skills0')
  await expect(page.locator('[aria-label="Practice summary"]')).toContainText('Retained skills0')
})

test('walkthrough preference is session-only and separate for each profile', async ({ page }) => {
  await page.goto('/#/home')
  await page.getByRole('button', { name: 'Try first rep walkthrough' }).click()
  const skip = help(page).getByRole('button', { name: 'Skip walkthrough' })
  await skip.focus()
  await skip.press('Enter')
  await expect(help(page)).toHaveCount(0)
  await expect(page.locator('#brief-section')).toBeFocused()
  expect(await page.evaluate(() => sessionStorage.getItem('code-reps:ui:default:first-rep-walkthrough'))).toBe('dismissed')
  expect(await page.evaluate(() => Object.keys(localStorage).some(key => key.includes('walkthrough')))).toBe(false)
  await page.getByRole('button', { name: 'Manage profiles' }).click()
  const dialog = page.getByRole('dialog', { name: 'Local profiles' })
  await dialog.getByText('Create or rename a profile', { exact: true }).click()
  await dialog.getByLabel('Profile name', { exact: true }).fill('Walkthrough learner')
  await dialog.getByRole('button', { name: 'Create profile', exact: true }).click()
  await expect(dialog.getByRole('status')).toHaveText('Profile created.')
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await page.goto('/#/home')
  await expect(page.getByRole('button', { name: 'Try first rep walkthrough' })).toBeVisible()
  await page.getByRole('button', { name: 'Try first rep walkthrough' }).click()
  await expect(help(page)).toContainText('1 of 5')
  await page.getByRole('button', { name: 'Manage profiles' }).click()
  await chooseOption(dialog.getByRole('combobox', { name: 'Switch profile', exact: true }), { label: 'My learning' })
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await page.goto('/#/practice/declare-variables')
  await expect(help(page)).toHaveCount(0)
  await page.goto('/#/history')
  await expect(page.getByText('No completed attempts yet. Finish a rep to save your first one here.', { exact: true })).toBeVisible()
})

test('an unavailable walkthrough leaves practice usable', async ({ page }) => {
  await page.route('**/src/FirstRepWalkthrough.tsx*', route => route.abort())
  await page.goto('/#/home')
  await page.getByRole('button', { name: 'Try first rep walkthrough' }).click()
  await expect(help(page)).toContainText('Reload to try again')
  await help(page).getByRole('button', { name: 'Skip walkthrough' }).click()
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.getByLabel('Your plan', { exact: true }).fill('Practice remains available')
  await saved(page)
})

for (const viewport of [{ width: 1280, height: 600 }, { width: 390, height: 600 }]) {
  test(`walkthrough leaves a usable desk at ${viewport.width}×${viewport.height}`, async ({ page }) => {
    await page.setViewportSize(viewport)
    await page.goto('/#/home')
    await page.getByRole('button', { name: 'Try first rep walkthrough' }).click()
    await help(page).getByRole('button', { name: 'Walkthrough: plan next' }).click()
    await page.getByLabel('Your plan', { exact: true }).fill('Keep my short-screen draft')
    await help(page).getByRole('button', { name: 'Walkthrough: solve next' }).click()
    await replaceCode(page, greeting, 'declare-variables')
    const geometry = await page.locator('.editor-wrap').evaluate(element => {
      const box = element.getBoundingClientRect()
      return { height: box.height, width: box.width }
    })
    expect(geometry.height).toBeGreaterThanOrEqual(120)
    expect(geometry.width).toBeGreaterThan(250)
    await expect(help(page).getByRole('button', { name: 'Skip walkthrough' })).toBeInViewport()
    await page.getByRole('button', { name: 'Run checks', exact: true }).click()
    await expectChecksFinished(page.getByText('All checks passed', { exact: true }))
    const skip = help(page).getByRole('button', { name: 'Skip walkthrough' })
    await skip.focus()
    await skip.press('Enter')
    await expect(page.locator('#solution-section')).toBeFocused()
    await page.reload()
    await page.getByRole('button', { name: 'Plan', exact: true }).click()
    await expect(page.getByLabel('Your plan', { exact: true })).toHaveValue('Keep my short-screen draft')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
}
