// Builds src/catalog-index.ts: the small synchronous catalog the app renders from at startup.
// The heavy rep and lesson payloads load on demand; tests/catalog-index.test.mjs fails when this file is stale.
import { repSources } from '../src/rep-sources.ts'
import { skills } from '../src/knowledge.ts'

const line = value => `  ${JSON.stringify(value)},`

export function renderCatalogIndex() {
  const repEntries = []
  const seen = new Set()
  for (const source of repSources) {
    for (const rep of source.reps) {
      if (seen.has(rep.id)) throw new Error(`Duplicate rep id ${rep.id}`)
      seen.add(rep.id)
      repEntries.push({ id: rep.id, title: rep.title, category: rep.category, ...(rep.format ? { format: rep.format } : {}), starter: rep.starter, hintTotal: rep.hints.length, source: source.name })
    }
  }
  const foundationRepIds = []
  for (const source of repSources) {
    for (const lesson of source.lessons ?? []) {
      if (!source.reps.some(rep => rep.id === lesson.repId)) throw new Error(`Lesson for ${lesson.repId} must live in the same source as its rep (${source.name})`)
      if (source.name === 'foundations') foundationRepIds.push(lesson.repId)
    }
  }
  const skillEntries = skills.map(skill => ({
    id: skill.id, title: skill.title, summary: skill.summary, prerequisites: skill.prerequisites, related: skill.related, repIds: skill.repIds,
    firstMistake: skill.mistakes[0] ?? '',
    questions: skill.questions.map(question => ({
      id: question.id, optionCount: question.options.length, answer: question.answer,
      ...(question.completion ? { completion: true, answerText: question.options[question.answer] } : {}),
    })),
  }))
  const names = repSources.map(source => `'${source.name}'`).join(' | ')
  return `// Generated by scripts/generate-catalog-index.mjs. Do not edit by hand: run \`yarn content:index\` after changing a rep or lesson.
// This is the small catalog the app renders from at startup. Heavy rep and lesson content loads on demand.
import type { Rep } from './rep-types.ts'

export type RepSourceName = ${names}
export type RepSummary = { id: string; title: string; category: string; format?: Rep['format']; starter: string; hintTotal: number; source: RepSourceName }
export type QuestionSummary = { id: string; optionCount: number; answer: number; completion?: true; answerText?: string }
export type SkillSummary = { id: string; title: string; summary: string; prerequisites: string[]; related: string[]; repIds: string[]; firstMistake: string; questions: QuestionSummary[] }

export const repIndex: RepSummary[] = [
${repEntries.map(line).join('\n')}
]

/** Foundations reps, in lesson order. Each has a short lesson before it. */
export const foundationRepIds: string[] = ${JSON.stringify(foundationRepIds)}

export const skillIndex: SkillSummary[] = [
${skillEntries.map(line).join('\n')}
]
`
}
