import type { Rep } from './rep.ts'

const sortRows = [
  { name: 'Pear', qty: 4 }, { name: 'apple', qty: 9 }, { name: 'Fig', qty: 4 }, { name: 'Apple', qty: 2 },
]

export const appReps: Rep[] = [
  {
    id: 'frontend-sort-table', title: 'Sort table rows', category: 'Frontend core', format: 'transform',
    context: 'A table lets people click a column header to sort. The table component needs the rows in display order, and the original list must stay untouched so other views can still use it.',
    prompt: 'Implement sortRows(rows, column, direction). Return a new array of the same row objects ordered by column, which is "name" or "qty". Names compare without case sensitivity; qty compares as numbers. direction "desc" reverses the order; any other direction value sorts ascending. Rows whose sort values are equal keep their original relative order in both directions. If column is not "name" or "qty", return a copy in the original order.',
    example: { input: 'sortRows([{name:"Pear",qty:4},{name:"Fig",qty:4}], "qty", "desc")', output: '[{name:"Pear",qty:4},{name:"Fig",qty:4}]' },
    note: 'Ties stay in original order even when the direction is descending, so do not simply reverse an ascending result. Compare lowercase names with < and >, not locale rules. Do not change the input array or its row objects. Authored tables have at most 200 rows with basic Latin names.',
    vocabulary: [{ term: 'Stable sort', meaning: 'a sort that keeps equal items in their original order' }, { term: 'Mutation', meaning: 'changing an existing array or object instead of making a new one' }],
    planPrompt: 'How will you compare two rows for each column? What should happen to two rows that tie when the direction is descending?',
    starter: 'type Row = { name: string; qty: number }\n\nfunction sortRows(rows: Row[], column: string, direction: string): Row[] {\n  // Return a new, ordered array.\n  return rows\n}\n',
    functionName: 'sortRows', preserveInput: true,
    hints: ['Work on a copy so the caller keeps its original order.', 'Decide a sort value per row first: lowercase name or the qty number.', 'Compare values to get -1, 0, or 1, flip only that result for "desc", and fall back to the original positions when the values are equal.'],
    checks: [
      { name: 'Sorts names ascending without case sensitivity', input: [sortRows, 'name', 'asc'], expected: [{ name: 'apple', qty: 9 }, { name: 'Apple', qty: 2 }, { name: 'Fig', qty: 4 }, { name: 'Pear', qty: 4 }] },
      { name: 'Sorts names descending and keeps tied names in original order', input: [sortRows, 'name', 'desc'], expected: [{ name: 'Pear', qty: 4 }, { name: 'Fig', qty: 4 }, { name: 'apple', qty: 9 }, { name: 'Apple', qty: 2 }] },
      { name: 'Sorts quantities ascending with stable ties', input: [sortRows, 'qty', 'asc'], expected: [{ name: 'Apple', qty: 2 }, { name: 'Pear', qty: 4 }, { name: 'Fig', qty: 4 }, { name: 'apple', qty: 9 }] },
      { name: 'Sorts quantities descending with stable ties', input: [sortRows, 'qty', 'desc'], expected: [{ name: 'apple', qty: 9 }, { name: 'Pear', qty: 4 }, { name: 'Fig', qty: 4 }, { name: 'Apple', qty: 2 }] },
      { name: 'Compares quantities as numbers, not text', input: [[{ name: 'a', qty: 10 }, { name: 'b', qty: 9 }], 'qty', 'asc'], expected: [{ name: 'b', qty: 9 }, { name: 'a', qty: 10 }] },
      { name: 'Treats an unknown direction as ascending', input: [[{ name: 'b', qty: 1 }, { name: 'a', qty: 2 }], 'name', 'up'], expected: [{ name: 'a', qty: 2 }, { name: 'b', qty: 1 }] },
      { name: 'Returns original order for an unknown column', input: [[{ name: 'b', qty: 1 }, { name: 'a', qty: 2 }], 'price', 'asc'], expected: [{ name: 'b', qty: 1 }, { name: 'a', qty: 2 }] },
      { name: 'Handles an empty table', input: [[], 'name', 'asc'], expected: [] },
      { name: 'Handles a single row', input: [[{ name: 'Solo', qty: 1 }], 'qty', 'desc'], expected: [{ name: 'Solo', qty: 1 }] },
    ],
  },
  {
    id: 'frontend-form-errors', title: 'Show form errors', category: 'Frontend core', format: 'transform',
    context: 'A sign-up form shows one message under each field. The form keeps every value as text, exactly as typed, and asks this function what to display.',
    prompt: 'Implement formErrors(values) for fields name, email, and age, all strings. Return an object with a key only for each field that has an error; return {} when everything is fine. Each field shows at most one message, chosen in this order. name: blank after trimming gives "Name is required"; more than 20 characters after trimming gives "Name must be 20 characters or fewer". email: blank after trimming gives "Email is required"; otherwise it must contain exactly one @ with nonblank text on both sides after trimming, or give "Enter a valid email address". age: blank after trimming gives "Age is required"; otherwise it must be digits only after trimming, or give "Age must be a whole number"; otherwise it must be from 18 through 120, or give "Age must be between 18 and 120".',
    example: { input: 'formErrors({name:" ", email:"ada@site", age:"17"})', output: '{name:"Name is required", age:"Age must be between 18 and 120"}' },
    note: 'Required beats format, and format beats range, so a field never reports two problems. Fields are checked independently. "007" is digits only and counts as 7. Do not change the values object. Authored values are at most 200 characters.',
    vocabulary: [{ term: 'Precedence', meaning: 'the order that decides which rule wins when several apply' }, { term: 'Derived data', meaning: 'a value calculated from the current inputs instead of stored separately' }],
    planPrompt: 'For one field, list its rules from first to last. What does age "1e3" or "-5" do, and which rule decides it?',
    starter: 'type Values = { name: string; email: string; age: string }\ntype Errors = { name?: string; email?: string; age?: string }\n\nfunction formErrors(values: Values): Errors {\n  // Return only the fields that have an error.\n  return {}\n}\n',
    functionName: 'formErrors', preserveInput: true,
    hints: ['Handle each field on its own and build the result object as you go.', 'Within a field, test the rules in the stated order and stop at the first failure.', 'Trim first; for age, test the digit pattern before converting to a number, then compare the number with both limits.'],
    checks: [
      { name: 'Returns an empty object for valid values', input: [{ name: ' Ada ', email: 'ada@site.test', age: '30' }], expected: {} },
      { name: 'Reports the example errors', input: [{ name: ' ', email: 'ada@site', age: '17' }], expected: { name: 'Name is required', age: 'Age must be between 18 and 120' } },
      { name: 'Reports required errors for blank fields', input: [{ name: '', email: ' \t', age: '  ' }], expected: { name: 'Name is required', email: 'Email is required', age: 'Age is required' } },
      { name: 'Accepts a 20-character name', input: [{ name: 'abcdefghijklmnopqrst', email: 'a@b', age: '18' }], expected: {} },
      { name: 'Rejects a 21-character name after trimming', input: [{ name: ' abcdefghijklmnopqrstu ', email: 'a@b', age: '18' }], expected: { name: 'Name must be 20 characters or fewer' } },
      { name: 'Rejects an email with no @', input: [{ name: 'Ada', email: 'ada.site', age: '20' }], expected: { email: 'Enter a valid email address' } },
      { name: 'Rejects an email with two @', input: [{ name: 'Ada', email: 'a@b@c', age: '20' }], expected: { email: 'Enter a valid email address' } },
      { name: 'Rejects an email with a blank side', input: [{ name: 'Ada', email: ' @b', age: '20' }], expected: { email: 'Enter a valid email address' } },
      { name: 'Prefers the format message over the range message', input: [{ name: 'Ada', email: 'a@b', age: '12.5' }], expected: { age: 'Age must be a whole number' } },
      { name: 'Rejects a negative or exponent age as not whole', input: [{ name: 'Ada', email: 'a@b', age: '-5' }], expected: { age: 'Age must be a whole number' } },
      { name: 'Accepts the age limits', input: [{ name: 'Ada', email: 'a@b', age: ' 120 ' }], expected: {} },
      { name: 'Rejects an age just above the limit', input: [{ name: 'Ada', email: 'a@b', age: '121' }], expected: { age: 'Age must be between 18 and 120' } },
      { name: 'Reads leading zeros as the number', input: [{ name: 'Ada', email: 'a@b', age: '007' }], expected: { age: 'Age must be between 18 and 120' } },
    ],
  },
  {
    id: 'frontend-pagination-controls', title: 'Choose page buttons', category: 'Frontend core', format: 'transform',
    context: 'A results list has many pages, so the pager cannot show a button for each one. It shows the first page, the last page, the current page and its neighbors, and "..." where pages are hidden.',
    prompt: 'Implement pageButtons(current, total). Return the items to show in order: page numbers and the string "...". If total is less than 1, return []. Otherwise clamp current into 1 through total. Show page 1, the last page, the clamped current page, and the pages directly before and after it (when they exist). Between two shown pages, if exactly one page is hidden, show that page number; if more than one is hidden, show "..." once. Never show a page twice.',
    example: { input: 'pageButtons(5, 10)', output: '[1, "...", 4, 5, 6, "...", 10]' },
    note: 'The ellipsis is the three-character string "..." (three periods). A single hidden page is shown rather than replaced by "...", so the pager never hides just one page. Both inputs are integers. Authored totals are at most 1000.',
    vocabulary: [{ term: 'Pagination', meaning: 'splitting a long list into numbered pages' }, { term: 'Ellipsis', meaning: 'the "..." mark showing that some pages are hidden' }],
    planPrompt: 'Which page numbers are always shown? How will you decide what goes between two shown pages that are not next to each other?',
    starter: 'function pageButtons(current: number, total: number): (number | string)[] {\n  // Return page numbers and "..." in display order.\n  return []\n}\n',
    functionName: 'pageButtons',
    hints: ['First decide the set of page numbers that are always shown, then put them in order without repeats.', 'Walk the ordered numbers and look at the gap between each one and the one before it.', 'A gap of 1 adds nothing, a gap of 2 adds the single hidden page, and a larger gap adds "...".'],
    checks: [
      { name: 'Shows both gaps in the middle', input: [5, 10], expected: [1, '...', 4, 5, 6, '...', 10] },
      { name: 'Shows a single hidden page instead of an ellipsis', input: [4, 10], expected: [1, 2, 3, 4, 5, '...', 10] },
      { name: 'Handles the first page', input: [1, 10], expected: [1, 2, '...', 10] },
      { name: 'Handles the last page', input: [10, 10], expected: [1, '...', 9, 10] },
      { name: 'Shows every page when the gaps are single pages', input: [4, 7], expected: [1, 2, 3, 4, 5, 6, 7] },
      { name: 'Handles a single page', input: [1, 1], expected: [1] },
      { name: 'Handles two pages', input: [2, 2], expected: [1, 2] },
      { name: 'Clamps current above total', input: [99, 10], expected: [1, '...', 9, 10] },
      { name: 'Clamps current below one', input: [-3, 10], expected: [1, 2, '...', 10] },
      { name: 'Returns nothing when there are no pages', input: [1, 0], expected: [] },
    ],
  },
  {
    id: 'backend-query-filters', title: 'Parse query filters', category: 'Backend core', format: 'backend',
    context: 'A list endpoint receives its URL query as a parsed object. Values arrive as text, may be missing, and may be repeated, so the handler must turn them into trusted filters before searching.',
    prompt: 'Implement parseFilters(query). Return {ok: false, error: "INVALID_QUERY"} unless query is a non-null object that is not an array. For each field, a missing, undefined, or blank (after trim) value uses its default. Any other non-string value, such as an array from a repeated parameter, is invalid. Check in this order. status: trimmed and lowercased, one of "open", "closed", "all"; default "all"; otherwise INVALID_STATUS. limit: trimmed, digits only, value from 1 through 50; default 10; otherwise INVALID_LIMIT. tag: trimmed and lowercased, at most 20 characters; default null; otherwise INVALID_TAG. On success return {ok: true, filters: {status, limit, tag}} with limit as a number. Errors have the form {ok: false, error}.',
    example: { input: 'parseFilters({status:" OPEN ", limit:"25"})', output: '{ok:true, filters:{status:"open", limit:25, tag:null}}' },
    note: 'Error precedence is query shape, then status, then limit, then tag. Do not guess a nearby value for an invalid one. Extra keys are ignored. "007" is digits only and means 7; "0", "51", "1.5", and "-2" are invalid. Do not change the query. Authored queries have at most 20 keys and values of at most 200 characters. These are parsed objects, not a live HTTP test.',
    vocabulary: [{ term: 'Query string', meaning: 'the ?key=value part of a URL, which carries text values' }, { term: 'Default', meaning: 'a specified value used when input is absent, rather than invalid' }],
    planPrompt: 'List each field with its default and its rule. Pick a request with two invalid fields and predict exactly which error you return.',
    starter: 'type Filters = { status: "open" | "closed" | "all"; limit: number; tag: string | null }\n\nfunction parseFilters(query: unknown): { ok: true; filters: Filters } | { ok: false; error: string } {\n  // Validate each field, applying defaults.\n  return { ok: false, error: "INVALID_QUERY" }\n}\n',
    functionName: 'parseFilters', preserveInput: true,
    hints: ['Reject non-objects and arrays before reading any field.', 'Write one small step per field that returns a default for missing or blank text and rejects other non-strings.', 'Convert limit to a number only after testing that it is digits, then check both bounds. Return fields in the stated error order.'],
    checks: [
      { name: 'Normalizes the example', input: [{ status: ' OPEN ', limit: '25' }], expected: { ok: true, filters: { status: 'open', limit: 25, tag: null } } },
      { name: 'Applies every default for an empty query', input: [{}], expected: { ok: true, filters: { status: 'all', limit: 10, tag: null } } },
      { name: 'Treats blank text as missing', input: [{ status: '  ', limit: '', tag: ' \t ' }], expected: { ok: true, filters: { status: 'all', limit: 10, tag: null } } },
      { name: 'Normalizes the tag and ignores extra keys', input: [{ tag: ' Urgent ', page: '2' }], expected: { ok: true, filters: { status: 'all', limit: 10, tag: 'urgent' } } },
      { name: 'Accepts the limit bounds', input: [{ limit: '50', status: 'closed' }], expected: { ok: true, filters: { status: 'closed', limit: 50, tag: null } } },
      { name: 'Reads leading zeros as the number', input: [{ limit: '007' }], expected: { ok: true, filters: { status: 'all', limit: 7, tag: null } } },
      { name: 'Accepts a 20-character tag', input: [{ tag: 'abcdefghijklmnopqrst' }], expected: { ok: true, filters: { status: 'all', limit: 10, tag: 'abcdefghijklmnopqrst' } } },
      { name: 'Rejects an unknown status', input: [{ status: 'done' }], expected: { ok: false, error: 'INVALID_STATUS' } },
      { name: 'Rejects a repeated parameter', input: [{ status: ['open', 'closed'] }], expected: { ok: false, error: 'INVALID_STATUS' } },
      { name: 'Rejects a limit of zero', input: [{ limit: '0' }], expected: { ok: false, error: 'INVALID_LIMIT' } },
      { name: 'Rejects a limit above the maximum', input: [{ limit: '51' }], expected: { ok: false, error: 'INVALID_LIMIT' } },
      { name: 'Rejects fractional and negative limits', input: [{ limit: '1.5' }], expected: { ok: false, error: 'INVALID_LIMIT' } },
      { name: 'Rejects a numeric value instead of text', input: [{ limit: 10 }], expected: { ok: false, error: 'INVALID_LIMIT' } },
      { name: 'Rejects a 21-character tag', input: [{ tag: 'abcdefghijklmnopqrstu' }], expected: { ok: false, error: 'INVALID_TAG' } },
      { name: 'Reports status before limit and tag', input: [{ status: 'x', limit: '0', tag: 'abcdefghijklmnopqrstu' }], expected: { ok: false, error: 'INVALID_STATUS' } },
      { name: 'Reports limit before tag', input: [{ limit: '0', tag: 'abcdefghijklmnopqrstu' }], expected: { ok: false, error: 'INVALID_LIMIT' } },
      { name: 'Rejects null', input: [null], expected: { ok: false, error: 'INVALID_QUERY' } },
      { name: 'Rejects an array', input: [['open']], expected: { ok: false, error: 'INVALID_QUERY' } },
      { name: 'Rejects a primitive', input: ['status=open'], expected: { ok: false, error: 'INVALID_QUERY' } },
    ],
  },
  {
    id: 'backend-rate-limit', title: 'Decide a rate limit', category: 'Backend core', format: 'backend',
    context: 'An API allows each caller a fixed number of requests per time window. The server keeps the times of the caller\'s earlier accepted requests; this function decides about one new request. The current time is passed in, so the function never reads a clock.',
    prompt: 'Implement rateLimit(times, now, limit, windowMs). Time is split into fixed windows that start at 0, windowMs, 2 * windowMs, and so on; the window containing now starts at Math.floor(now / windowMs) * windowMs and lasts windowMs milliseconds. Count the earlier times that are inside the same window as now and are not later than now. If that count is less than limit, return {allowed: true, remaining: limit - count - 1, retryAfterMs: 0}. Otherwise return {allowed: false, remaining: 0, retryAfterMs: the time left until the next window starts}.',
    example: { input: 'rateLimit([1000, 1500], 1800, 4, 1000)', output: '{allowed:true, remaining:1, retryAfterMs:0}' },
    note: 'A time exactly at a window start belongs to that new window, so a request at 2000 with windowMs 1000 starts fresh. Times from earlier windows do not count. Times later than now are ignored. Times may be in any order. limit and windowMs are positive integers; now and times are nonnegative integers. Do not change the times array. Authored lists have at most 200 times.',
    vocabulary: [{ term: 'Fixed window', meaning: 'counting requests in time slots with fixed start times' }, { term: 'Injected time', meaning: 'passing the current time in as an argument so the code is easy to test' }],
    planPrompt: 'Where does the current window start and end? Which recorded times count toward the limit, and what is exactly on the boundary?',
    starter: 'type Decision = { allowed: boolean; remaining: number; retryAfterMs: number }\n\nfunction rateLimit(times: number[], now: number, limit: number, windowMs: number): Decision {\n  // Decide whether this request is allowed.\n  return { allowed: false, remaining: 0, retryAfterMs: 0 }\n}\n',
    functionName: 'rateLimit', preserveInput: true,
    hints: ['Start by working out where the current window begins and where the next one begins.', 'Count only the times that fall between the window start and now.', 'Compare that count with limit; when blocked, the wait is the next window start minus now.'],
    checks: [
      { name: 'Allows a request and reports what remains', input: [[1000, 1500], 1800, 4, 1000], expected: { allowed: true, remaining: 1, retryAfterMs: 0 } },
      { name: 'Allows the first request with no history', input: [[], 0, 2, 1000], expected: { allowed: true, remaining: 1, retryAfterMs: 0 } },
      { name: 'Allows the last request under the limit', input: [[1000, 1200], 1400, 3, 1000], expected: { allowed: true, remaining: 0, retryAfterMs: 0 } },
      { name: 'Blocks when the window is full', input: [[1000, 1200, 1300], 1400, 3, 1000], expected: { allowed: false, remaining: 0, retryAfterMs: 600 } },
      { name: 'Starts fresh exactly at the next window', input: [[1000, 1200, 1300], 2000, 3, 1000], expected: { allowed: true, remaining: 2, retryAfterMs: 0 } },
      { name: 'Blocks one millisecond before the next window', input: [[1000, 1200, 1300], 1999, 3, 1000], expected: { allowed: false, remaining: 0, retryAfterMs: 1 } },
      { name: 'Counts a time exactly at the window start', input: [[1000], 1500, 1, 1000], expected: { allowed: false, remaining: 0, retryAfterMs: 500 } },
      { name: 'Ignores times from earlier windows', input: [[100, 900, 999], 1000, 1, 1000], expected: { allowed: true, remaining: 0, retryAfterMs: 0 } },
      { name: 'Ignores times later than now', input: [[1900, 1800], 1100, 1, 1000], expected: { allowed: true, remaining: 0, retryAfterMs: 0 } },
      { name: 'Accepts unordered times', input: [[1900, 1100, 1500], 1950, 3, 1000], expected: { allowed: false, remaining: 0, retryAfterMs: 50 } },
      { name: 'Uses the supplied window size', input: [[10, 20], 25, 2, 30], expected: { allowed: false, remaining: 0, retryAfterMs: 5 } },
    ],
  },
  {
    id: 'backend-error-response', title: 'Map errors to responses', category: 'Backend core', format: 'backend',
    context: 'Application code throws errors with a short code. The API must turn each one into an HTTP status and a message that is safe to show clients, without leaking messages, stack traces, or database details.',
    prompt: 'Implement errorResponse(error). If error is a non-null object whose own code property is one of the known strings below, return {status, body: {error: code, message}}. NOT_FOUND gives 404 "We could not find that item."; INVALID_INPUT gives 400 "The request was not valid."; UNAUTHENTICATED gives 401 "Please sign in first."; FORBIDDEN gives 403 "You do not have access to this."; CONFLICT gives 409 "That change conflicts with the current data." For anything else return {status: 500, body: {error: "INTERNAL", message: "Something went wrong. Please try again later."}}.',
    example: { input: 'errorResponse({code:"NOT_FOUND", message:"row 7 missing in orders"})', output: '{status:404, body:{error:"NOT_FOUND", message:"We could not find that item."}}' },
    note: 'Codes match exactly, including case. The body has only error and message: never copy the thrown error\'s own message, stack, or other fields. Unknown codes, a code that is not a string, a missing code, null, strings, and plain Error objects all produce the 500 response. A code like "toString" or "constructor" is not known. Do not change the error.',
    vocabulary: [{ term: 'Status code', meaning: 'the number in an HTTP response that says how the request went' }, { term: 'Information leak', meaning: 'exposing internal details such as stack traces to people who should not see them' }],
    planPrompt: 'What are the five known codes and their responses? What should a caller see for an error you did not plan for, and why not show its message?',
    starter: 'type ErrorBody = { status: number; body: { error: string; message: string } }\n\nfunction errorResponse(error: unknown): ErrorBody {\n  // Map known codes; hide everything else.\n  return { status: 500, body: { error: "INTERNAL", message: "" } }\n}\n',
    functionName: 'errorResponse', preserveInput: true,
    hints: ['Check that the value is an object before reading a code from it.', 'Look the code up in a table you write yourself, but make sure inherited names like "toString" are not treated as known.', 'Build the response from your table only, so thrown text can never reach the body.'],
    checks: [
      { name: 'Maps the example without leaking its message', input: [{ code: 'NOT_FOUND', message: 'row 7 missing in orders' }], expected: { status: 404, body: { error: 'NOT_FOUND', message: 'We could not find that item.' } } },
      { name: 'Maps invalid input', input: [{ code: 'INVALID_INPUT' }], expected: { status: 400, body: { error: 'INVALID_INPUT', message: 'The request was not valid.' } } },
      { name: 'Maps unauthenticated', input: [{ code: 'UNAUTHENTICATED' }], expected: { status: 401, body: { error: 'UNAUTHENTICATED', message: 'Please sign in first.' } } },
      { name: 'Maps forbidden', input: [{ code: 'FORBIDDEN' }], expected: { status: 403, body: { error: 'FORBIDDEN', message: 'You do not have access to this.' } } },
      { name: 'Maps conflict and drops extra fields', input: [{ code: 'CONFLICT', stack: 'at db.query', sql: 'UPDATE orders' }], expected: { status: 409, body: { error: 'CONFLICT', message: 'That change conflicts with the current data.' } } },
      { name: 'Hides an unknown code', input: [{ code: 'DB_TIMEOUT', message: 'connection to 10.0.0.5 failed' }], expected: { status: 500, body: { error: 'INTERNAL', message: 'Something went wrong. Please try again later.' } } },
      { name: 'Matches codes with exact case', input: [{ code: 'not_found' }], expected: { status: 500, body: { error: 'INTERNAL', message: 'Something went wrong. Please try again later.' } } },
      { name: 'Does not treat inherited names as known codes', input: [{ code: 'toString' }], expected: { status: 500, body: { error: 'INTERNAL', message: 'Something went wrong. Please try again later.' } } },
      { name: 'Ignores a code that is not a string', input: [{ code: 404 }], expected: { status: 500, body: { error: 'INTERNAL', message: 'Something went wrong. Please try again later.' } } },
      { name: 'Handles an object with no code', input: [{ message: 'boom' }], expected: { status: 500, body: { error: 'INTERNAL', message: 'Something went wrong. Please try again later.' } } },
      { name: 'Handles null', input: [null], expected: { status: 500, body: { error: 'INTERNAL', message: 'Something went wrong. Please try again later.' } } },
      { name: 'Handles a thrown string', input: ['NOT_FOUND'], expected: { status: 500, body: { error: 'INTERNAL', message: 'Something went wrong. Please try again later.' } } },
    ],
  },
]
