import type { Rep } from './rep.ts'
import type { RepDepth } from './rep-depth.ts'

const sortRows = [
  { name: 'Pear', qty: 4 }, { name: 'apple', qty: 9 }, { name: 'Fig', qty: 4 }, { name: 'Apple', qty: 2 },
]

export const appReps: Rep[] = [
  {
    id: 'frontend-sort-table', title: 'Sort table rows', category: 'Frontend core', format: 'transform',
    context: 'A table lets people click a column header to sort. The table component needs the rows in display order, and the original list must stay untouched so other views can still use it.',
    prompt: 'Implement sortRows(rows, column, direction). Return a new array of the same row objects ordered by column, which is "name" or "qty". Names compare without case sensitivity; qty compares as numbers. direction "desc" reverses the order; any other direction value sorts ascending. Rows whose sort values are equal keep their original relative order in both directions. If column is not "name" or "qty", return a copy in the original order.',
    example: { input: 'sortRows([{name:"Pear",qty:4},{name:"Fig",qty:4}], "qty", "desc")', output: '[{name:"Pear",qty:4},{name:"Fig",qty:4}]' },
    note: 'Ties stay in original order even when the direction is descending, so do not simply reverse an ascending result. Compare lowercase names with < and >, not locale rules. Do not change the input array or its row objects. Authored tables have at most 200 rows with basic Latin names.',
    vocabulary: [{ term: 'Stable sort', meaning: 'a sort that keeps equal items in their original order' }, { term: 'Mutation', meaning: 'changing an existing array or object instead of making a new one' }],
    planPrompt: 'How will you compare two rows for each column? What should happen to two rows that tie when the direction is descending?',
    starter: 'type Row = { name: string; qty: number }\n\nfunction sortRows(rows: Row[], column: string, direction: string): Row[] {\n  // Return a new, ordered array.\n  return rows\n}\n',
    functionName: 'sortRows', preserveInput: true,
    hints: ['Work on a copy so the caller keeps its original order.', 'Decide a sort value per row first: lowercase name or the qty number.', 'Compare values to get -1, 0, or 1, flip only that result for "desc", and fall back to the original positions when the values are equal.'],
    checks: [
      { name: 'Sorts names ascending without case sensitivity', input: [sortRows, 'name', 'asc'], expected: [{ name: 'apple', qty: 9 }, { name: 'Apple', qty: 2 }, { name: 'Fig', qty: 4 }, { name: 'Pear', qty: 4 }] },
      { name: 'Sorts names descending and keeps tied names in original order', input: [sortRows, 'name', 'desc'], expected: [{ name: 'Pear', qty: 4 }, { name: 'Fig', qty: 4 }, { name: 'apple', qty: 9 }, { name: 'Apple', qty: 2 }] },
      { name: 'Sorts quantities ascending with stable ties', input: [sortRows, 'qty', 'asc'], expected: [{ name: 'Apple', qty: 2 }, { name: 'Pear', qty: 4 }, { name: 'Fig', qty: 4 }, { name: 'apple', qty: 9 }] },
      { name: 'Sorts quantities descending with stable ties', input: [sortRows, 'qty', 'desc'], expected: [{ name: 'apple', qty: 9 }, { name: 'Pear', qty: 4 }, { name: 'Fig', qty: 4 }, { name: 'Apple', qty: 2 }] },
      { name: 'Compares quantities as numbers, not text', input: [[{ name: 'a', qty: 10 }, { name: 'b', qty: 9 }], 'qty', 'asc'], expected: [{ name: 'b', qty: 9 }, { name: 'a', qty: 10 }] },
      { name: 'Treats an unknown direction as ascending', input: [[{ name: 'b', qty: 1 }, { name: 'a', qty: 2 }], 'name', 'up'], expected: [{ name: 'a', qty: 2 }, { name: 'b', qty: 1 }] },
      { name: 'Returns original order for an unknown column', input: [[{ name: 'b', qty: 1 }, { name: 'a', qty: 2 }], 'price', 'asc'], expected: [{ name: 'b', qty: 1 }, { name: 'a', qty: 2 }] },
      { name: 'Handles an empty table', input: [[], 'name', 'asc'], expected: [] },
      { name: 'Handles a single row', input: [[{ name: 'Solo', qty: 1 }], 'qty', 'desc'], expected: [{ name: 'Solo', qty: 1 }] },
    ],
  },
  {
    id: 'frontend-form-errors', title: 'Show form errors', category: 'Frontend core', format: 'transform',
    context: 'A sign-up form shows one message under each field. The form keeps every value as text, exactly as typed, and asks this function what to display.',
    prompt: 'Implement formErrors(values) for fields name, email, and age, all strings. Return an object with a key only for each field that has an error; return {} when everything is fine. Each field shows at most one message, chosen in this order. name: blank after trimming gives "Name is required"; more than 20 characters after trimming gives "Name must be 20 characters or fewer". email: blank after trimming gives "Email is required"; otherwise it must contain exactly one @ with nonblank text on both sides after trimming, or give "Enter a valid email address". age: blank after trimming gives "Age is required"; otherwise it must be digits only after trimming, or give "Age must be a whole number"; otherwise it must be from 18 through 120, or give "Age must be between 18 and 120".',
    example: { input: 'formErrors({name:" ", email:"ada@site", age:"17"})', output: '{name:"Name is required", age:"Age must be between 18 and 120"}' },
    note: 'Required beats format, and format beats range, so a field never reports two problems. Fields are checked independently. "007" is digits only and counts as 7. Do not change the values object. Authored values are at most 200 characters.',
    vocabulary: [{ term: 'Precedence', meaning: 'the order that decides which rule wins when several apply' }, { term: 'Derived data', meaning: 'a value calculated from the current inputs instead of stored separately' }],
    planPrompt: 'For one field, list its rules from first to last. What does age "1e3" or "-5" do, and which rule decides it?',
    starter: 'type Values = { name: string; email: string; age: string }\ntype Errors = { name?: string; email?: string; age?: string }\n\nfunction formErrors(values: Values): Errors {\n  // Return only the fields that have an error.\n  return {}\n}\n',
    functionName: 'formErrors', preserveInput: true,
    hints: ['Handle each field on its own and build the result object as you go.', 'Within a field, test the rules in the stated order and stop at the first failure.', 'Trim first; for age, test the digit pattern before converting to a number, then compare the number with both limits.'],
    checks: [
      { name: 'Returns an empty object for valid values', input: [{ name: ' Ada ', email: 'ada@site.test', age: '30' }], expected: {} },
      { name: 'Reports the example errors', input: [{ name: ' ', email: 'ada@site', age: '17' }], expected: { name: 'Name is required', age: 'Age must be between 18 and 120' } },
      { name: 'Reports required errors for blank fields', input: [{ name: '', email: ' \t', age: '  ' }], expected: { name: 'Name is required', email: 'Email is required', age: 'Age is required' } },
      { name: 'Accepts a 20-character name', input: [{ name: 'abcdefghijklmnopqrst', email: 'a@b', age: '18' }], expected: {} },
      { name: 'Rejects a 21-character name after trimming', input: [{ name: ' abcdefghijklmnopqrstu ', email: 'a@b', age: '18' }], expected: { name: 'Name must be 20 characters or fewer' } },
      { name: 'Rejects an email with no @', input: [{ name: 'Ada', email: 'ada.site', age: '20' }], expected: { email: 'Enter a valid email address' } },
      { name: 'Rejects an email with two @', input: [{ name: 'Ada', email: 'a@b@c', age: '20' }], expected: { email: 'Enter a valid email address' } },
      { name: 'Rejects an email with a blank side', input: [{ name: 'Ada', email: ' @b', age: '20' }], expected: { email: 'Enter a valid email address' } },
      { name: 'Prefers the format message over the range message', input: [{ name: 'Ada', email: 'a@b', age: '12.5' }], expected: { age: 'Age must be a whole number' } },
      { name: 'Rejects a negative or exponent age as not whole', input: [{ name: 'Ada', email: 'a@b', age: '-5' }], expected: { age: 'Age must be a whole number' } },
      { name: 'Accepts the age limits', input: [{ name: 'Ada', email: 'a@b', age: ' 120 ' }], expected: {} },
      { name: 'Rejects an age just above the limit', input: [{ name: 'Ada', email: 'a@b', age: '121' }], expected: { age: 'Age must be between 18 and 120' } },
      { name: 'Reads leading zeros as the number', input: [{ name: 'Ada', email: 'a@b', age: '007' }], expected: { age: 'Age must be between 18 and 120' } },
    ],
  },
  {
    id: 'frontend-pagination-controls', title: 'Choose page buttons', category: 'Frontend core', format: 'transform',
    context: 'A results list has many pages, so the pager cannot show a button for each one. It shows the first page, the last page, the current page and its neighbors, and "..." where pages are hidden.',
    prompt: 'Implement pageButtons(current, total). Return the items to show in order: page numbers and the string "...". If total is less than 1, return []. Otherwise clamp current into 1 through total. Show page 1, the last page, the clamped current page, and the pages directly before and after it (when they exist). Between two shown pages, if exactly one page is hidden, show that page number; if more than one is hidden, show "..." once. Never show a page twice.',
    example: { input: 'pageButtons(5, 10)', output: '[1, "...", 4, 5, 6, "...", 10]' },
    note: 'The ellipsis is the three-character string "..." (three periods). A single hidden page is shown rather than replaced by "...", so the pager never hides just one page. Both inputs are integers. Authored totals are at most 1000.',
    vocabulary: [{ term: 'Pagination', meaning: 'splitting a long list into numbered pages' }, { term: 'Ellipsis', meaning: 'the "..." mark showing that some pages are hidden' }],
    planPrompt: 'Which page numbers are always shown? How will you decide what goes between two shown pages that are not next to each other?',
    starter: 'function pageButtons(current: number, total: number): (number | string)[] {\n  // Return page numbers and "..." in display order.\n  return []\n}\n',
    functionName: 'pageButtons',
    hints: ['First decide the set of page numbers that are always shown, then put them in order without repeats.', 'Walk the ordered numbers and look at the gap between each one and the one before it.', 'A gap of 1 adds nothing, a gap of 2 adds the single hidden page, and a larger gap adds "...".'],
    checks: [
      { name: 'Shows both gaps in the middle', input: [5, 10], expected: [1, '...', 4, 5, 6, '...', 10] },
      { name: 'Shows a single hidden page instead of an ellipsis', input: [4, 10], expected: [1, 2, 3, 4, 5, '...', 10] },
      { name: 'Handles the first page', input: [1, 10], expected: [1, 2, '...', 10] },
      { name: 'Handles the last page', input: [10, 10], expected: [1, '...', 9, 10] },
      { name: 'Shows every page when the gaps are single pages', input: [4, 7], expected: [1, 2, 3, 4, 5, 6, 7] },
      { name: 'Handles a single page', input: [1, 1], expected: [1] },
      { name: 'Handles two pages', input: [2, 2], expected: [1, 2] },
      { name: 'Clamps current above total', input: [99, 10], expected: [1, '...', 9, 10] },
      { name: 'Clamps current below one', input: [-3, 10], expected: [1, 2, '...', 10] },
      { name: 'Returns nothing when there are no pages', input: [1, 0], expected: [] },
    ],
  },
  {
    id: 'backend-query-filters', title: 'Parse query filters', category: 'Backend core', format: 'backend',
    context: 'A list endpoint receives its URL query as a parsed object. Values arrive as text, may be missing, and may be repeated, so the handler must turn them into trusted filters before searching.',
    prompt: 'Implement parseFilters(query). Return {ok: false, error: "INVALID_QUERY"} unless query is a non-null object that is not an array. For each field, a missing, undefined, or blank (after trim) value uses its default. Any other non-string value, such as an array from a repeated parameter, is invalid. Check in this order. status: trimmed and lowercased, one of "open", "closed", "all"; default "all"; otherwise INVALID_STATUS. limit: trimmed, digits only, value from 1 through 50; default 10; otherwise INVALID_LIMIT. tag: trimmed and lowercased, at most 20 characters; default null; otherwise INVALID_TAG. On success return {ok: true, filters: {status, limit, tag}} with limit as a number. Errors have the form {ok: false, error}.',
    example: { input: 'parseFilters({status:" OPEN ", limit:"25"})', output: '{ok:true, filters:{status:"open", limit:25, tag:null}}' },
    note: 'Error precedence is query shape, then status, then limit, then tag. Do not guess a nearby value for an invalid one. Extra keys are ignored. "007" is digits only and means 7; "0", "51", "1.5", and "-2" are invalid. Do not change the query. Authored queries have at most 20 keys and values of at most 200 characters. These are parsed objects, not a live HTTP test.',
    vocabulary: [{ term: 'Query string', meaning: 'the ?key=value part of a URL, which carries text values' }, { term: 'Default', meaning: 'a specified value used when input is absent, rather than invalid' }],
    planPrompt: 'List each field with its default and its rule. Pick a request with two invalid fields and predict exactly which error you return.',
    starter: 'type Filters = { status: "open" | "closed" | "all"; limit: number; tag: string | null }\n\nfunction parseFilters(query: unknown): { ok: true; filters: Filters } | { ok: false; error: string } {\n  // Validate each field, applying defaults.\n  return { ok: false, error: "INVALID_QUERY" }\n}\n',
    functionName: 'parseFilters', preserveInput: true,
    hints: ['Reject non-objects and arrays before reading any field.', 'Write one small step per field that returns a default for missing or blank text and rejects other non-strings.', 'Convert limit to a number only after testing that it is digits, then check both bounds. Return fields in the stated error order.'],
    checks: [
      { name: 'Normalizes the example', input: [{ status: ' OPEN ', limit: '25' }], expected: { ok: true, filters: { status: 'open', limit: 25, tag: null } } },
      { name: 'Applies every default for an empty query', input: [{}], expected: { ok: true, filters: { status: 'all', limit: 10, tag: null } } },
      { name: 'Treats blank text as missing', input: [{ status: '  ', limit: '', tag: ' \t ' }], expected: { ok: true, filters: { status: 'all', limit: 10, tag: null } } },
      { name: 'Normalizes the tag and ignores extra keys', input: [{ tag: ' Urgent ', page: '2' }], expected: { ok: true, filters: { status: 'all', limit: 10, tag: 'urgent' } } },
      { name: 'Accepts the limit bounds', input: [{ limit: '50', status: 'closed' }], expected: { ok: true, filters: { status: 'closed', limit: 50, tag: null } } },
      { name: 'Reads leading zeros as the number', input: [{ limit: '007' }], expected: { ok: true, filters: { status: 'all', limit: 7, tag: null } } },
      { name: 'Accepts a 20-character tag', input: [{ tag: 'abcdefghijklmnopqrst' }], expected: { ok: true, filters: { status: 'all', limit: 10, tag: 'abcdefghijklmnopqrst' } } },
      { name: 'Rejects an unknown status', input: [{ status: 'done' }], expected: { ok: false, error: 'INVALID_STATUS' } },
      { name: 'Rejects a repeated parameter', input: [{ status: ['open', 'closed'] }], expected: { ok: false, error: 'INVALID_STATUS' } },
      { name: 'Rejects a limit of zero', input: [{ limit: '0' }], expected: { ok: false, error: 'INVALID_LIMIT' } },
      { name: 'Rejects a limit above the maximum', input: [{ limit: '51' }], expected: { ok: false, error: 'INVALID_LIMIT' } },
      { name: 'Rejects fractional and negative limits', input: [{ limit: '1.5' }], expected: { ok: false, error: 'INVALID_LIMIT' } },
      { name: 'Rejects a numeric value instead of text', input: [{ limit: 10 }], expected: { ok: false, error: 'INVALID_LIMIT' } },
      { name: 'Rejects a 21-character tag', input: [{ tag: 'abcdefghijklmnopqrstu' }], expected: { ok: false, error: 'INVALID_TAG' } },
      { name: 'Reports status before limit and tag', input: [{ status: 'x', limit: '0', tag: 'abcdefghijklmnopqrstu' }], expected: { ok: false, error: 'INVALID_STATUS' } },
      { name: 'Reports limit before tag', input: [{ limit: '0', tag: 'abcdefghijklmnopqrstu' }], expected: { ok: false, error: 'INVALID_LIMIT' } },
      { name: 'Rejects null', input: [null], expected: { ok: false, error: 'INVALID_QUERY' } },
      { name: 'Rejects an array', input: [['open']], expected: { ok: false, error: 'INVALID_QUERY' } },
      { name: 'Rejects a primitive', input: ['status=open'], expected: { ok: false, error: 'INVALID_QUERY' } },
    ],
  },
  {
    id: 'backend-rate-limit', title: 'Decide a rate limit', category: 'Backend core', format: 'backend',
    context: 'An API allows each caller a fixed number of requests per time window. The server keeps the times of the caller\'s earlier accepted requests; this function decides about one new request. The current time is passed in, so the function never reads a clock.',
    prompt: 'Implement rateLimit(times, now, limit, windowMs). Time is split into fixed windows that start at 0, windowMs, 2 * windowMs, and so on; the window containing now starts at Math.floor(now / windowMs) * windowMs and lasts windowMs milliseconds. Count the earlier times that are inside the same window as now and are not later than now. If that count is less than limit, return {allowed: true, remaining: limit - count - 1, retryAfterMs: 0}. Otherwise return {allowed: false, remaining: 0, retryAfterMs: the time left until the next window starts}.',
    example: { input: 'rateLimit([1000, 1500], 1800, 4, 1000)', output: '{allowed:true, remaining:1, retryAfterMs:0}' },
    note: 'A time exactly at a window start belongs to that new window, so a request at 2000 with windowMs 1000 starts fresh. Times from earlier windows do not count. Times later than now are ignored. Times may be in any order. limit and windowMs are positive integers; now and times are nonnegative integers. Do not change the times array. Authored lists have at most 200 times.',
    vocabulary: [{ term: 'Fixed window', meaning: 'counting requests in time slots with fixed start times' }, { term: 'Injected time', meaning: 'passing the current time in as an argument so the code is easy to test' }],
    planPrompt: 'Where does the current window start and end? Which recorded times count toward the limit, and what is exactly on the boundary?',
    starter: 'type Decision = { allowed: boolean; remaining: number; retryAfterMs: number }\n\nfunction rateLimit(times: number[], now: number, limit: number, windowMs: number): Decision {\n  // Decide whether this request is allowed.\n  return { allowed: false, remaining: 0, retryAfterMs: 0 }\n}\n',
    functionName: 'rateLimit', preserveInput: true,
    hints: ['Start by working out where the current window begins and where the next one begins.', 'Count only the times that fall between the window start and now.', 'Compare that count with limit; when blocked, the wait is the next window start minus now.'],
    checks: [
      { name: 'Allows a request and reports what remains', input: [[1000, 1500], 1800, 4, 1000], expected: { allowed: true, remaining: 1, retryAfterMs: 0 } },
      { name: 'Allows the first request with no history', input: [[], 0, 2, 1000], expected: { allowed: true, remaining: 1, retryAfterMs: 0 } },
      { name: 'Allows the last request under the limit', input: [[1000, 1200], 1400, 3, 1000], expected: { allowed: true, remaining: 0, retryAfterMs: 0 } },
      { name: 'Blocks when the window is full', input: [[1000, 1200, 1300], 1400, 3, 1000], expected: { allowed: false, remaining: 0, retryAfterMs: 600 } },
      { name: 'Starts fresh exactly at the next window', input: [[1000, 1200, 1300], 2000, 3, 1000], expected: { allowed: true, remaining: 2, retryAfterMs: 0 } },
      { name: 'Blocks one millisecond before the next window', input: [[1000, 1200, 1300], 1999, 3, 1000], expected: { allowed: false, remaining: 0, retryAfterMs: 1 } },
      { name: 'Counts a time exactly at the window start', input: [[1000], 1500, 1, 1000], expected: { allowed: false, remaining: 0, retryAfterMs: 500 } },
      { name: 'Ignores times from earlier windows', input: [[100, 900, 999], 1000, 1, 1000], expected: { allowed: true, remaining: 0, retryAfterMs: 0 } },
      { name: 'Ignores times later than now', input: [[1900, 1800], 1100, 1, 1000], expected: { allowed: true, remaining: 0, retryAfterMs: 0 } },
      { name: 'Accepts unordered times', input: [[1900, 1100, 1500], 1950, 3, 1000], expected: { allowed: false, remaining: 0, retryAfterMs: 50 } },
      { name: 'Uses the supplied window size', input: [[10, 20], 25, 2, 30], expected: { allowed: false, remaining: 0, retryAfterMs: 5 } },
    ],
  },
  {
    id: 'backend-error-response', title: 'Map errors to responses', category: 'Backend core', format: 'backend',
    context: 'Application code throws errors with a short code. The API must turn each one into an HTTP status and a message that is safe to show clients, without leaking messages, stack traces, or database details.',
    prompt: 'Implement errorResponse(error). If error is a non-null object whose own code property is one of the known strings below, return {status, body: {error: code, message}}. NOT_FOUND gives 404 "We could not find that item."; INVALID_INPUT gives 400 "The request was not valid."; UNAUTHENTICATED gives 401 "Please sign in first."; FORBIDDEN gives 403 "You do not have access to this."; CONFLICT gives 409 "That change conflicts with the current data." For anything else return {status: 500, body: {error: "INTERNAL", message: "Something went wrong. Please try again later."}}.',
    example: { input: 'errorResponse({code:"NOT_FOUND", message:"row 7 missing in orders"})', output: '{status:404, body:{error:"NOT_FOUND", message:"We could not find that item."}}' },
    note: 'Codes match exactly, including case. The body has only error and message: never copy the thrown error\'s own message, stack, or other fields. Unknown codes, a code that is not a string, a missing code, null, strings, and plain Error objects all produce the 500 response. A code like "toString" or "constructor" is not known. Do not change the error.',
    vocabulary: [{ term: 'Status code', meaning: 'the number in an HTTP response that says how the request went' }, { term: 'Information leak', meaning: 'exposing internal details such as stack traces to people who should not see them' }],
    planPrompt: 'What are the five known codes and their responses? What should a caller see for an error you did not plan for, and why not show its message?',
    starter: 'type ErrorBody = { status: number; body: { error: string; message: string } }\n\nfunction errorResponse(error: unknown): ErrorBody {\n  // Map known codes; hide everything else.\n  return { status: 500, body: { error: "INTERNAL", message: "" } }\n}\n',
    functionName: 'errorResponse', preserveInput: true,
    hints: ['Check that the value is an object before reading a code from it.', 'Look the code up in a table you write yourself, but make sure inherited names like "toString" are not treated as known.', 'Build the response from your table only, so thrown text can never reach the body.'],
    checks: [
      { name: 'Maps the example without leaking its message', input: [{ code: 'NOT_FOUND', message: 'row 7 missing in orders' }], expected: { status: 404, body: { error: 'NOT_FOUND', message: 'We could not find that item.' } } },
      { name: 'Maps invalid input', input: [{ code: 'INVALID_INPUT' }], expected: { status: 400, body: { error: 'INVALID_INPUT', message: 'The request was not valid.' } } },
      { name: 'Maps unauthenticated', input: [{ code: 'UNAUTHENTICATED' }], expected: { status: 401, body: { error: 'UNAUTHENTICATED', message: 'Please sign in first.' } } },
      { name: 'Maps forbidden', input: [{ code: 'FORBIDDEN' }], expected: { status: 403, body: { error: 'FORBIDDEN', message: 'You do not have access to this.' } } },
      { name: 'Maps conflict and drops extra fields', input: [{ code: 'CONFLICT', stack: 'at db.query', sql: 'UPDATE orders' }], expected: { status: 409, body: { error: 'CONFLICT', message: 'That change conflicts with the current data.' } } },
      { name: 'Hides an unknown code', input: [{ code: 'DB_TIMEOUT', message: 'connection to 10.0.0.5 failed' }], expected: { status: 500, body: { error: 'INTERNAL', message: 'Something went wrong. Please try again later.' } } },
      { name: 'Matches codes with exact case', input: [{ code: 'not_found' }], expected: { status: 500, body: { error: 'INTERNAL', message: 'Something went wrong. Please try again later.' } } },
      { name: 'Does not treat inherited names as known codes', input: [{ code: 'toString' }], expected: { status: 500, body: { error: 'INTERNAL', message: 'Something went wrong. Please try again later.' } } },
      { name: 'Ignores a code that is not a string', input: [{ code: 404 }], expected: { status: 500, body: { error: 'INTERNAL', message: 'Something went wrong. Please try again later.' } } },
      { name: 'Handles an object with no code', input: [{ message: 'boom' }], expected: { status: 500, body: { error: 'INTERNAL', message: 'Something went wrong. Please try again later.' } } },
      { name: 'Handles null', input: [null], expected: { status: 500, body: { error: 'INTERNAL', message: 'Something went wrong. Please try again later.' } } },
      { name: 'Handles a thrown string', input: ['NOT_FOUND'], expected: { status: 500, body: { error: 'INTERNAL', message: 'Something went wrong. Please try again later.' } } },
    ],
  },
]

export const appGuides = {
  'frontend-sort-table': {
    plan: ['Choose a comparable value for each column.', 'Sort a copy, not the caller\'s array.', 'Decide how ties behave in both directions.'],
    explanation: ['Trace two tied rows through an ascending and a descending sort.', 'Explain why reversing the ascending result changes tie order.', 'Account for the sorting cost and the copy.'],
    example: 'I copy the rows with their original positions, pick a lowercase name or a number as the sort value, and compare values. For descending I flip only the value comparison, then use the original position to break ties. Sorting costs O(n log n) time and O(n) extra space; the input is never changed. These checks do not show that the table looks or announces its sort order correctly.',
  },
  'frontend-form-errors': {
    plan: ['List each field\'s rules in precedence order.', 'Trim before testing blank, length, and shape.', 'Add a key only when a field has an error.'],
    explanation: ['Trace a field that breaks two rules and say which message wins.', 'Explain why digits are tested before the range.', 'Say what this does not cover, such as when messages first appear.'],
    example: 'For each field I trim, then check required, format, and range in that order and stop at the first failure. I add only failing fields to a new object. Work scales with text length. The checks cover the stated rules; when to show an error, focus, and screen-reader announcements need separate review.',
  },
  'frontend-pagination-controls': {
    plan: ['Decide which page numbers are always shown.', 'Order them without repeats.', 'Decide what fills each gap.'],
    explanation: ['Trace a middle page and a page near an end.', 'Explain why one hidden page is shown instead of an ellipsis.', 'State how out-of-range current values are handled.'],
    example: 'I clamp current, collect the first, last, current and neighbor pages, sort them, and walk the list. A gap of two adds the hidden page, a larger gap adds "...". The work depends on a handful of pages, not on total. Passing checks does not prove the buttons are keyboard operable or labelled for assistive technology.',
  },
  'backend-query-filters': {
    plan: ['Write each field\'s default and rule.', 'Reject non-string values before normalizing.', 'Follow the stated error order.'],
    explanation: ['Trace a query with two invalid fields.', 'Explain missing-or-blank versus invalid.', 'Explain why a repeated parameter is rejected.'],
    example: 'I reject a bad query shape, then validate status, limit, and tag in order. Missing or blank text uses a default; other non-strings are invalid. Limit is checked as digits before conversion, then against 1 through 50. Work scales with value length. The checks use parsed objects and do not test real URL parsing or a database.',
  },
  'backend-rate-limit': {
    plan: ['Find the start and end of the current window.', 'Count only times inside that window and not after now.', 'Compute the wait from the next window start.'],
    explanation: ['Trace requests just before and exactly at a window boundary.', 'Explain the burst a fixed window allows across a boundary.', 'Explain why time is passed in.'],
    example: 'I compute the window start with floor division, count the recorded times from that start up to now, and compare with the limit. When blocked I return the time until start plus windowMs. One scan costs O(n). A fixed window can allow a double burst around a boundary; these checks cover the decision only, not storage or concurrent requests.',
  },
  'backend-error-response': {
    plan: ['List the known codes and their responses.', 'Treat everything else as an internal error.', 'Build the body only from your own table.'],
    explanation: ['Trace a known code with extra fields and an unknown code.', 'Explain what could leak if the thrown message were copied.', 'Explain why inherited property names need care.'],
    example: 'I check the error is an object with an own string code, look that code up in a table I wrote, and return the table\'s status and message. Anything else gets the generic 500 response. Thrown text never reaches the body. The lookup is O(1). This tests the mapping only, not logging or real HTTP responses.',
  },
}

export const appDepth: Record<string, RepDepth> = {
  'frontend-sort-table': {
    reasoning: 'Each row gets a sort key and its original position. Ordering by key then position gives a total order, so equal rows are ordered the same way every time, in either direction.',
    trace: 'Rows Pear/4 (position 0) and Fig/4 (position 2) tie on qty. Descending flips only the key comparison, so apple/9 comes first, then Pear before Fig by position, then Apple/2.',
    alternative: 'Array.prototype.sort on a copy is stable in modern engines, so ascending ties already keep order; descending still needs a comparator that does not reverse ties. Sorting only on demand costs O(n log n) per click; keeping the table presorted trades storage for faster clicks.',
    counterexample: 'Sorting ascending then calling reverse() puts tied rows in reverse order, so Fig would come before Pear. Calling sort directly on the input also reorders the caller\'s list.',
    transfer: 'Add a second sort column so ties on the first column use the second. State which column wins and how direction applies to each before coding. This changed contract is self-reviewed, not checked by the original cases.',
  },
  'frontend-form-errors': {
    reasoning: 'Each field is a short ordered list of rules, and the first failing rule supplies the only message. Required, then format, then range makes later rules safe to apply, since a number is only read after the text is known to be digits.',
    trace: 'For age "12.5": not blank, so skip required; the digit pattern fails on the dot, so the message is "Age must be a whole number". The range rule never runs. For age "007": digits pass, the value 7 is below 18, so the range message appears.',
    alternative: 'A list of rule functions per field is easy to extend for large forms; direct if statements are easier to read for three fields. Collecting all messages per field would change the contract by showing several at once.',
    counterexample: 'Number(age) turns " " into 0 and "1e2" into 100, so blank or exponent text slips past the rules. Testing range before format reports a range error for "-5" instead of a format error.',
    transfer: 'Add a password field that must match a confirm field. Decide which field carries the mismatch message and where it sits in precedence. This changed contract is self-reviewed, not checked by the original cases.',
  },
  'frontend-pagination-controls': {
    reasoning: 'The always-shown pages form a small ordered set with no repeats. Any two neighbors in that set have a gap, and the gap size alone decides the output: nothing, the one hidden page, or an ellipsis.',
    trace: 'For current 4, total 10 the set is 1, 3, 4, 5, 10. The gap from 1 to 3 hides only page 2, so show 2. The gap from 5 to 10 hides four pages, so show "...". Result: 1 2 3 4 5 ... 10.',
    alternative: 'Building the list from numeric ranges (left edge, middle window, right edge) works but needs separate cases for pages near each end. The set-and-gap method has one rule for every position at the cost of a small sort.',
    counterexample: 'Always inserting "..." for any gap shows "1 ... 3" and hides one page the ellipsis could have shown. Forgetting to clamp current 99 of 10 shows neighbors 98 and 100.',
    transfer: 'Show two neighbors on each side instead of one. State what the single-hidden-page rule becomes and test the first and last pages. This changed contract is self-reviewed, not checked by the original cases.',
  },
  'backend-query-filters': {
    reasoning: 'Query values are untrusted text, so each field is validated in a fixed order and only then converted. Separating "absent, so use the default" from "present but invalid, so reject" keeps defaults from hiding mistakes.',
    trace: 'For {status: "x", limit: "0"}, the query is an object; status "x" is not allowed, so return INVALID_STATUS before limit is looked at. For {limit: " 007 "} trim gives "007", digits pass, the number is 7 and within 1 to 50.',
    alternative: 'A schema library centralizes rules for many endpoints; explicit steps keep this small contract visible. Clamping an out-of-range limit to 50 is friendlier but would change the contract by accepting what this one rejects.',
    counterexample: 'Number("") is 0 and Number("1.5") is 1.5, so converting first lets blank or fractional limits through. Using limit || 10 turns an explicit invalid "0" into the default instead of an error.',
    transfer: 'Add a sort parameter with allowed values and a default, and decide whether it comes before or after tag in the error order. This changed contract is self-reviewed, not checked by the original cases.',
  },
  'backend-rate-limit': {
    reasoning: 'Within one window the decision depends only on how many earlier times fall in [start, now]. The window start comes from floor division, so every time maps to exactly one window and a boundary time belongs to the later window.',
    trace: 'With windowMs 1000, limit 3, and times [1000, 1200, 1300]: at now 1999 all three count, so the answer is blocked with retry 1 ms. At now 2000 the window starts at 2000, none of the times count, and the request is allowed with remaining 2.',
    alternative: 'A sliding window counts requests in the last windowMs milliseconds and avoids the boundary burst, but needs more bookkeeping. A fixed window is simpler and stores one count per window if you keep a counter instead of every time.',
    counterexample: 'Counting times in the last windowMs (now - windowMs) instead of the aligned window blocks the request at 2000 above, though a fresh window has begun. Counting times later than now includes impossible future requests.',
    transfer: 'Change to a sliding window and compute how long to wait for the oldest counted request to expire. Define the boundary rule first. This changed contract is self-reviewed, not checked by the original cases.',
  },
  'backend-error-response': {
    reasoning: 'The response is built only from a table the server author controls, so internal text can never reach the client. Unknown input falls to a single safe default, which means a new unplanned error fails closed.',
    trace: 'For {code: "CONFLICT", sql: "UPDATE orders ..."}, the own string code CONFLICT is in the table, so return 409 and the table message; sql is never read. For {code: "toString"}, the name is not an own table key, so the result is the 500 response.',
    alternative: 'A switch on the code is explicit and avoids inherited-property traps; a Map or an object with Object.hasOwn is shorter for many codes. Returning error.message would be convenient but exposes internals.',
    counterexample: 'Looking up table[error.code] on a plain object finds inherited names such as toString or constructor and returns a function instead of a response. Spreading the error into the body copies stack and sql fields.',
    transfer: 'Add a validation error that carries field names the client may see. Decide which parts of the thrown error are safe and how the table stays the only source of text. This changed contract is self-reviewed, not checked by the original cases.',
  },
}
