import { practicalSkills } from './practical-concepts.ts'
export type Question = { completion?: boolean; id: string; prompt: string; code: string; options: string[]; answer: number; explanation: string }
export type Skill = { id: string; title: string; summary: string; prerequisites: string[]; objectives: string[]; sections: { title: string; body: string }[]; example: string; walkthrough: string[]; mistakes: string[]; questions: Question[]; repIds: string[]; related: string[] }
const q = (id: string, prompt: string, code: string, options: string[], answer: number, explanation: string): Question => ({ id, prompt, code, options, answer, explanation })
export const skills: Skill[] = [
  {
    id: 'values', title: 'Values, types, and functions', summary: 'Name information, describe its shape, and return a result from a function.', prerequisites: [],
    objectives: ['Distinguish a value from the name referring to it.', 'Choose a type for a function input and output.', 'Explain return versus printing and reassignment versus mutation.'],
    sections: [
      { title: 'Names and values', body: 'A variable names a value. const prevents assigning a different value to that name; it does not freeze an object. let allows reassignment. Choose names that describe the role of the value, such as quantity, rather than its type alone.' },
      { title: 'Types describe expectations', body: 'string, number, and boolean describe common values. TypeScript checks your program before it runs, but its types do not validate data received over a network. A function signature describes expected inputs and the value it returns.' },
      { title: 'A function is a boundary', body: 'A function takes inputs and returns an output. console.log displays something for a person; return sends a value back to the caller. Keep calculation separate from display so you can check the calculation directly.' },
    ],
    example: 'function cost(price: number, quantity: number): number {\n  return price * quantity\n}\nconst subtotal = cost(250, 2) // 500',
    walkthrough: ['The caller supplies 250 and 2.', 'Inside cost, price is 250 and quantity is 2.', 'Multiplication produces 500; return passes it to the caller.', 'subtotal names the returned value. No output is printed.'],
    mistakes: ['Using console.log where the caller expects a return value.', 'Assuming const makes an array immutable.', 'Treating TypeScript annotations as runtime validation.'],
    questions: [q('return', 'What value does result contain?', 'function twice(n: number) { return n * 2 }\nconst result = twice(3)', ['3', '6', 'undefined'], 1, 'The returned value is 3 multiplied by 2. Printing is not involved.'), q('const', 'Which operation is allowed?', 'const names = ["Ada"]', ['names = []', 'names.push("Bo")', 'Neither'], 1, 'const prevents reassignment of names, but the array can still change.')],
    repIds: ['declare-variables', 'basic-types', 'create-objects', 'make-arrays', 'write-functions'], related: ['arrays', 'validation'],
  },
  {
    id: 'arrays', title: 'Arrays and one-pass reasoning', summary: 'Follow an ordered collection, keep a useful invariant, and handle boundaries.', prerequisites: ['values'],
    objectives: ['Trace every iteration, including empty input.', 'Distinguish selection, counting, and transformation.', 'Explain time and extra storage for a single scan.'],
    sections: [
      { title: 'Order and position', body: 'An array stores ordered values. Position zero holds the first item. Reading past the end produces undefined. Before reading an item, decide what an empty array means for your contract: zero, null, an empty result, or an error.' },
      { title: 'Keep an invariant', body: 'An invariant is a fact that remains true while a loop runs. In a counting loop, count equals the number of qualifying values already visited. Start at zero, update only when the condition holds, and return after visiting all inputs.' },
      { title: 'Choose the operation', body: 'filter selects existing items; map transforms every item; reduce accumulates a result. A plain loop is often easiest to trace. Use the clearest form for the task. One scan over n items is O(n); an output array can require O(n) space.' },
    ],
    example: 'function countPositive(numbers: number[]) {\n  let count = 0\n  for (const n of numbers) {\n    if (n > 0) count++\n  }\n  return count\n}\ncountPositive([-2, 4, 0, 3]) // 2',
    walkthrough: ['Before the loop, count is 0.', '-2 does not qualify: count stays 0.', '4 qualifies: count becomes 1.', '0 does not qualify: count stays 1.', '3 qualifies: count becomes 2. Empty input would leave count at 0.'],
    mistakes: ['Using >= when the contract says strictly greater.', 'Returning inside the loop before all items are visited.', 'Mutating the source while deriving a result.'],
    questions: [q('scan', 'What is the final count?', 'let count = 0\nfor (const n of [0, -2, 3, 4]) {\n  if (n % 2 === 0) count++\n}', ['2', '3', '4'], 1, 'Zero, -2, and 4 are even. Negative values and zero still satisfy remainder zero.'), { ...q('boundary', 'Complete the condition: type n > limit, n >= limit, or n !== limit.', 'if (___) count++', ['n >= limit', 'n > limit', 'n !== limit'], 1, 'Strictly above excludes values equal to the limit. !== also includes smaller values.'), completion: true }],
    repIds: ['sum-positive-numbers', 'count-even-numbers', 'count-above-threshold', 'sum-matching-prices', 'count-open-tickets'], related: ['text', 'lookup', 'complexity'],
  },
  {
    id: 'text', title: 'Text and normalization', summary: 'Separate comparison rules from display values and define what counts as a word.', prerequisites: ['arrays'],
    objectives: ['Explain trimming versus removing internal whitespace.', 'Preserve original text when normalizing a comparison.', 'State character and case assumptions explicitly.'],
    sections: [
      { title: 'Normalization follows a contract', body: 'trim removes whitespace at the beginning and end. It does not remove spaces in the middle. Lowercasing can make a comparison case-insensitive, but should not silently change the text shown to a person. Decide whether blank text should be ignored, rejected, or kept.' },
      { title: 'Words and characters', body: 'For a whitespace-separated word exercise, trim first, handle empty input, then split on one or more whitespace characters. JavaScript strings use UTF-16 code units; length and index access are not a general count of human-visible characters. State a restricted alphabet when the exercise depends on that distinction.' },
      { title: 'Cost includes string work', body: 'Trimming, searching, and changing case inspect text. A loop over n labels is not necessarily O(n) independent of their length. Explain work in terms of total text processed when that matters.' },
    ],
    example: 'const original = " Ada "\nconst comparison = original.trim().toLowerCase()\ncomparison === "ada" // true\noriginal // still " Ada "',
    walkthrough: ['original holds the display value.', 'trim produces Ada without surrounding spaces.', 'toLowerCase produces ada for comparison.', 'The original string remains unchanged.'],
    mistakes: ['Counting an empty split result as one word.', 'Normalizing output when only comparison should change.', 'Assuming string.length always counts visible characters.'],
    questions: [q('trim', 'What does trim return?', '"  Ada Bo  ".trim()', ['"AdaBo"', '"Ada Bo"', '"  Ada Bo"'], 1, 'Only surrounding whitespace is removed; the space between names stays.'), q('blank', 'How many whitespace-separated words are present?', '"   \t  "', ['0', '1', '2'], 0, 'There is no non-whitespace text. Handle this before splitting.')],
    repIds: ['count-words', 'first-long-word', 'count-long-words', 'first-unique-character', 'first-label-ending', 'count-label-prefix'], related: ['lookup', 'frontend'],
  },
  {
    id: 'lookup', title: 'Maps, sets, and lookup', summary: 'Remember seen values, count occurrences, and preserve the required order.', prerequisites: ['arrays'],
    objectives: ['Choose a Set for membership or a Map for associated values.', 'Resolve ties according to the contract.', 'Explain the extra storage used by lookup collections.'],
    sections: [
      { title: 'Membership versus counting', body: 'A Set stores distinct values and answers whether one was seen. A Map associates a key with a value, such as a count. For each item, read the previous count or zero, then add one. Object keys have reference identity; two separate objects with identical fields are different keys.' },
      { title: 'Order belongs to the question', body: 'The first value that repeats is identified by its second occurrence, not the first position of any value that eventually repeats. Scan in input order and check membership before inserting. A most-frequent task needs an explicit rule for ties.' },
      { title: 'Tradeoffs', body: 'Lookup avoids repeatedly scanning a list. Common implementations give efficient average access; these exercises describe expected lookup costs rather than promise a universal worst-case O(1). Remembering k distinct values requires O(k) space.' },
    ],
    example: 'const seen = new Set<number>()\nfor (const n of [5, 2, 2, 5]) {\n  if (seen.has(n)) { /* first repeat is 2 */ break }\n  seen.add(n)\n}',
    walkthrough: ['5 is new: seen becomes {5}.', '2 is new: seen becomes {5, 2}.', 'The next 2 is already present, so it is the first repeat.', 'The later 5 does not change which repeat happened first.'],
    mistakes: ['Adding before checking membership.', 'Forgetting the tie rule.', 'Comparing separate object keys as if equal fields imply equal identity.'],
    questions: [q('repeat', 'Which value repeats first during the scan?', '[8, 3, 3, 8]', ['8', '3', 'Neither'], 1, 'The second 3 occurs before the second 8.'), { ...q('count', 'Complete the update: use (counts.get(key) ?? 0) + 1 for an initial zero.', 'counts.set(key, ___)', ['counts.get(key) + 1', '(counts.get(key) ?? 0) + 1', '1'], 1, 'Missing counts are undefined. Use zero as the initial count, then increment.'), completion: true }],
    repIds: ['has-duplicate', 'most-frequent-number', 'first-repeated-number', 'first-duplicate-label', 'count-statuses'], related: ['text', 'complexity'],
  },
  {
    id: 'stacks', title: 'Stacks and nested structure', summary: 'Match the most recent unfinished item before earlier items.', prerequisites: ['arrays'],
    objectives: ['Explain last-in, first-out order.', 'Trace unmatched openings and mismatched closings.', 'Distinguish counting from structural matching.'],
    sections: [
      { title: 'Last in, first out', body: 'A stack stores unfinished work in the order it must be resolved. push adds to the top; pop removes the top. Nested brackets need the latest opening to match the next closing. Counting alone cannot distinguish ([)] from ([]).' },
      { title: 'Three failure cases', body: 'Reject a closing with no opening, a closing of the wrong kind, and leftover openings at the end. For just one bracket kind, a counter can be enough: it must never be negative and must finish at zero.' },
      { title: 'Adjacent cancellation', body: 'A stack also supports removing adjacent equal pairs. Removing a pair exposes the earlier top, which can form a new pair with the next character. This avoids repeatedly rescanning the whole string.' },
    ],
    example: 'const stack: string[] = []\n// For ([]): push (, push [, pop [ for ], pop ( for ).\n// At the end the stack is empty.',
    walkthrough: ['( starts unfinished work.', '[ is nested inside it and becomes the top.', '] must match [, not the earlier (. ', ') matches the remaining (. Nothing is left.'],
    mistakes: ['Checking only equal counts of openings and closings.', 'Accepting leftover openings.', 'Removing from the front instead of the top.'],
    questions: [q('nested', 'Which input has matching counts but invalid nesting?', '', ['([])', '([)]', '()[]'], 1, 'The ) arrives while [ is the most recent unfinished opening.'), q('pop', 'What is returned by pop?', 'const stack = ["a", "b"]\nstack.pop()', ['"a"', '"b"', '["a", "b"]'], 1, 'pop removes and returns the last item.')],
    repIds: ['valid-parentheses', 'balanced-brackets', 'remove-adjacent-pairs', 'remaining-actions', 'cancel-adjacent-ids'], related: ['debugging', 'complexity'],
  },
  {
    id: 'validation', title: 'Runtime validation and API boundaries', summary: 'Turn unknown input into trusted data through explicit checks.', prerequisites: ['values'],
    objectives: ['Guard shape before accessing properties.', 'Separate validation from normalization.', 'Define predictable error responses and paging rules.'],
    sections: [
      { title: 'Unknown is honest', body: 'A request can contain null, an array, a primitive, or an object with unexpected fields. Check object shape before accessing fields. typeof null is object, so explicitly exclude null. Array.isArray distinguishes arrays from records.' },
      { title: 'Validate, then normalize', body: 'A type assertion changes what TypeScript believes; it does not inspect data. Check field types, acceptable bounds, and allowed values. Then trim or lowercase only as the contract requires. Return a new trusted object instead of modifying the input.' },
      { title: 'Predictable responses', body: 'Use clear success and failure shapes. A missing query differs from a malformed query. For paging, validate or normalize page and size before calculating (page - 1) * size. State whether invalid values are rejected or clamped.' },
    ],
    example: 'function readName(input: unknown): string | null {\n  if (!input || typeof input !== "object" || Array.isArray(input)) return null\n  if (!("name" in input) || typeof input.name !== "string") return null\n  const name = input.name.trim()\n  return name ? name : null\n}',
    walkthrough: ['Reject absent values, primitives, and arrays.', 'Check that name exists and is text.', 'Trim the value, then reject a blank result.', 'Return trusted text without changing the request.'],
    mistakes: ['Accessing a property before guarding null.', 'Accepting NaN or fractional numbers where integers are required.', 'Using as to pretend untrusted input is valid.'],
    questions: [q('null', 'What does typeof null return?', 'typeof null', ['"null"', '"undefined"', '"object"'], 2, 'This JavaScript behavior means an object check alone does not rule out null.'), q('integer', 'Which value fails an integer age contract?', '', ['0', '24.5', '120'], 1, '24.5 is fractional. Bounds alone would not catch it.')],
    repIds: ['backend-validate-user', 'backend-page-results', 'backend-ticket-handler', 'project-ticket-api', 'validate-page-query', 'interview-backend'], related: ['http', 'testing'],
  },
  {
    id: 'frontend', title: 'Frontend state and derived data', summary: 'Represent loading, errors, empty results, and ready content without conflicting UI.', prerequisites: ['arrays', 'text'],
    objectives: ['State request-state precedence explicitly.', 'Derive filtered output from source data and query.', 'Build labelled, keyboard-operable controls and insert text safely.'],
    sections: [
      { title: 'State precedence', body: 'Decide what a person should see while data is unresolved. A loading request should not look like a loaded empty result. In our exercises, loading wins, then a nonempty error, then empty or ready content. Other products may choose stale content while reloading; that must be an explicit contract.' },
      { title: 'Derived values', body: 'A filtered list can be calculated from source items and a query. Keeping another independently updated copy creates synchronization problems. Normalize comparison values, preserve original labels and order, and avoid mutating props or source objects.' },
      { title: 'Interaction is part of correctness', body: 'Use a real label associated with its input. Buttons should be reachable with Tab and activated by keyboard. Insert untrusted labels through textContent, not innerHTML. Behavioral checks help, but readable layout, focus visibility, and screen-reader use require manual review.' },
    ],
    example: 'const query = " AD ".trim().toLowerCase()\nconst visible = people.filter(person =>\n  person.name.toLowerCase().includes(query)\n)',
    walkthrough: ['Normalize the query once.', 'Compare each name using the same case rule.', 'Keep matching original objects in their original order.', 'Render an empty message only after the request has resolved.'],
    mistakes: ['Showing empty content during loading.', 'Lowercasing the displayed label.', 'Using clickable divs instead of buttons.', 'Rendering names as HTML.'],
    questions: [q('precedence', 'Which state should this exercise display?', '{ loading: true, error: "Offline", count: 0 }', ['Empty', 'Error', 'Loading'], 2, 'Loading has priority under the authored contract.'), q('derive', 'Where should the filtered list come from?', '', ['Source items and the current query', 'An unrelated saved copy', 'A mutation of the source array'], 0, 'Deriving output avoids maintaining conflicting copies of the same information.')],
    repIds: ['frontend-visible-items', 'frontend-view-state', 'frontend-directory', 'project-team-directory', 'interview-frontend', 'derive-task-summary'], related: ['react', 'async', 'testing'],
  },
  {
    id: 'debugging', title: 'Debugging, reading, and safe refactoring', summary: 'Establish behavior before changing code and preserve evidence of the repair.', prerequisites: ['arrays'],
    objectives: ['Separate expected behavior from observed behavior.', 'Trace a minimal input through existing code.', 'Use regression checks while improving structure.'],
    sections: [
      { title: 'Reproduce before repairing', body: 'Start from a concrete bug report: input, expected result, actual result. Reduce it to the smallest case that still exposes the problem. Write a hypothesis about the responsible operation and trace the values before changing code.' },
      { title: 'Read code as execution', body: 'Record the current value after each step rather than guessing from names. A correct-looking name can hide a reversed condition. For pipelines, trace normalization, filtering, lookup, and output independently. Predict before running the code.' },
      { title: 'Refactoring preserves the contract', body: 'A refactor improves structure without changing required behavior. First run existing checks, then change a small part and rerun. Review naming and duplication separately: passing tests does not prove readability or complete behavioral equivalence.' },
    ],
    example: '// Bug: ignores quantity\nsubtotal += item.priceCents\n// Trace: 250 cents × 2 units should contribute 500 cents.\n// Repair: multiply only after checking availability.',
    walkthrough: ['Choose one available item with quantity two.', 'The old calculation contributes only one unit of price.', 'The contract requires price multiplied by quantity.', 'Keep regression cases for unavailable items and discount application.'],
    mistakes: ['Changing several conditions before testing a hypothesis.', 'Repairing the example while breaking empty input.', 'Calling any rewrite a refactor despite changed behavior.'],
    questions: [q('regression', 'What is the most useful first check for the reported bug?', 'Bug: quantity two is charged as one.', ['Two units of one available item', 'Only an empty cart', 'A screenshot of the editor'], 0, 'The check directly reproduces the incorrect multiplication behavior.'), q('refactor', 'What must a behavior-preserving refactor keep?', '', ['Every variable name', 'The required observable behavior', 'The exact number of loops'], 1, 'Structure may change; the contract must stay intact.')],
    repIds: ['repair-visible-count', 'debug-cart-total', 'read-batch-labels', 'read-unique-names', 'refactor-stock-summary', 'debug-page-offset'], related: ['testing', 'complexity'],
  },
  {
    id: 'complexity', title: 'Time, space, and tradeoffs', summary: 'Explain how work grows and separate output storage from extra working memory.', prerequisites: ['arrays', 'lookup'],
    objectives: ['Define n before stating a complexity.', 'Recognize scans, nested scans, and sorting.', 'Include text processing and output size in the analysis.'],
    sections: [
      { title: 'Growth, not a stopwatch', body: 'Big O describes how resource use grows with input size. O(n) is a bound on growth, not a promise about milliseconds. Define n: item count, total character count, or another relevant size. Two consecutive scans are still O(n); nested scans can be O(n²).' },
      { title: 'Storage has a purpose', body: 'An accumulator uses O(1) extra working space. Remembering distinct inputs can use O(n). An output containing every matching item also needs space; say whether your analysis includes it. Avoid claiming constant space while building a result array.' },
      { title: 'Explain your tradeoff', body: 'Sorting is commonly O(n log n) for comparison-based implementations, but JavaScript does not guarantee a particular algorithm. A lookup collection spends memory to avoid repeated searches. Choose a readable solution first, then justify optimization with input sizes and measurements.' },
    ],
    example: 'for (const n of numbers) { /* first scan */ }\nfor (const n of numbers) { /* second scan */ }\n// 2n visits: O(n), not O(n²)',
    walkthrough: ['Let n be the number of inputs.', 'Each loop visits n items.', 'The loops run consecutively, for 2n visits.', 'Constant factors do not change linear growth.'],
    mistakes: ['Multiplying costs of consecutive loops.', 'Ignoring a growing output array.', 'Treating Big O as measured runtime.'],
    questions: [q('loops', 'What is the growth of two consecutive full scans?', 'scan(items)\nscan(items)', ['O(1)', 'O(n)', 'O(n²)'], 1, 'The work adds to 2n, which grows linearly.'), q('output', 'How much output storage can filtering require?', 'items.filter(matches)', ['Always O(1)', 'Up to O(n)', 'Always O(n²)'], 1, 'If every item matches, the new array contains n references.')],
    repIds: ['most-frequent-number', 'refactor-stock-summary', 'interview-frontend'], related: ['testing', 'stacks'],
  },
  {
    id: 'async', title: 'Promises and asynchronous work', summary: 'Understand completion, failure, and ordering without assuming background work has finished.', prerequisites: ['values'],
    objectives: ['Distinguish a Promise from its fulfilled value.', 'Use await and handle rejection.', 'Choose sequential or concurrent independent work intentionally.'],
    sections: [
      { title: 'A promise represents future completion', body: 'An async function returns a Promise. await pauses that async function until the promise settles; it does not block the entire browser. A rejected promise throws at the await expression and can be handled with try/catch.' },
      { title: 'Ordering and independence', body: 'Awaiting one request before starting another makes them sequential. Promise.all can start independent work together and rejects when an input rejects. Promise.allSettled records every outcome. Concurrency is useful only when operations do not depend on each other.' },
      { title: 'Races and cancellation', body: 'An older request can finish after a newer one. Track which request owns the visible state before applying a response. AbortController can cancel supported operations; cancellation still needs cleanup and should not be shown as an ordinary failure.' },
    ],
    example: 'async function loadName() {\n  try {\n    const response = await fetch("/name")\n    if (!response.ok) throw new Error("Request failed")\n    return await response.json()\n  } catch {\n    return null\n  }\n}',
    walkthrough: ['Calling loadName returns a Promise.', 'fetch settles when a response is available.', 'HTTP failure requires an explicit response.ok check.', 'Parsing also returns a Promise and can fail.', 'The catch handles either failure in this example.'],
    mistakes: ['Using a Promise as though it were its result.', 'Assuming fetch rejects on every HTTP error.', 'Letting an old response overwrite newer state.'],
    questions: [q('async-result', 'What does calling an async function return?', 'async function value() { return 4 }\nvalue()', ['4 directly', 'A Promise', 'undefined'], 1, 'Even an immediate returned value is wrapped in a Promise.'), q('fetch', 'How should a 404 response be detected?', '', ['Only through catch', 'By checking response.ok or status', 'It always means invalid JSON'], 1, 'fetch normally resolves for HTTP error responses; check the status explicitly.')],
    repIds: ['promise-outcomes', 'frontend-view-state', 'frontend-directory'], related: ['http', 'frontend', 'react', 'event-loop', 'request-ownership'],
  },
  {
    id: 'http', title: 'HTTP requests and response contracts', summary: 'Understand methods, status codes, payloads, and validation at a service boundary.', prerequisites: ['validation'],
    objectives: ['Distinguish transport success from application success.', 'Choose status codes consistent with the contract.', 'Explain pagination and error payloads.'],
    sections: [
      { title: 'Requests and responses', body: 'A request has a method, URL, headers, and sometimes a body. A response has a status, headers, and sometimes a body. GET is intended for retrieval; POST often creates or invokes work. HTTP conventions help clients, but each API still needs a precise contract.' },
      { title: 'Failures are data too', body: 'A malformed query should produce a predictable client error. A missing resource differs from an unexpected server failure. Error payloads should identify a stable reason and expose useful field information without leaking internal details.' },
      { title: 'Stable pagination', body: 'Define page numbering, maximum size, ordering, and total-count meaning. Apply filtering before calculating the matching total and page slice. Without deterministic ordering, adjacent pages can be inconsistent even when offsets are correct.' },
    ],
    example: 'GET /tickets?status=open&page=2&size=2\n// Filter first; total is all matching tickets.\n// Offset is (2 - 1) * 2 = 2.\n// Return matching items at positions 2 and 3.',
    walkthrough: ['Validate query shape and allowed values.', 'Filter tickets by the requested status.', 'Count all matches before slicing.', 'Return the requested slice and paging metadata.'],
    mistakes: ['Paging before filtering.', 'Reporting page length as the matching total.', 'Returning an ordinary success payload for malformed input.'],
    questions: [q('offset', 'What is the offset for page 3 with size 2?', '', ['3', '4', '6'], 1, '(page - 1) * size gives 4 for one-based pages.'), q('total', 'What should total represent in this contract?', '', ['Only items on the page', 'All matching items before paging', 'All items regardless of filters'], 1, 'Clients need the count of all matches to understand remaining pages.')],
    repIds: ['backend-ticket-handler', 'backend-page-results', 'validate-page-query', 'debug-page-offset'], related: ['async', 'databases', 'testing'],
  },
  {
    id: 'react', title: 'React state and effects', summary: 'Keep source state minimal and synchronize with external systems deliberately.', prerequisites: ['frontend', 'async'],
    objectives: ['Distinguish props, source state, and derived values.', 'Explain immutable state updates.', 'Recognize an effect that needs cleanup.'],
    sections: [
      { title: 'Source state versus derived output', body: 'Props are supplied by the parent. State records information that changes through interaction or external events. A filtered list can usually be derived from props and query while rendering; storing it separately can make it stale.' },
      { title: 'Updates and identity', body: 'Treat state objects and arrays as immutable. Create a new array when replacing one item. When an update depends on previous state, use the functional updater form. Stable keys identify list items across changes; position keys are risky when items reorder.' },
      { title: 'Effects synchronize', body: 'An effect synchronizes with something outside rendering: a subscription, timer, or network operation. It is not needed for every calculation. Return cleanup for subscriptions and timers, and prevent obsolete requests from owning current state. Development Strict Mode helps expose incomplete cleanup.' },
    ],
    example: 'const [query, setQuery] = useState("")\nconst visible = items.filter(item =>\n  item.name.toLowerCase().includes(query.toLowerCase())\n)\n// No second state variable is needed for visible.',
    walkthrough: ['items comes from the parent.', 'query is source state changed by typing.', 'visible is recalculated from the current inputs.', 'Rendering does not need an effect to derive this value.'],
    mistakes: ['Mutating an existing state array.', 'Using effects to keep redundant state synchronized.', 'Leaving timers or subscriptions running after unmount.'],
    questions: [q('derived-react', 'Does a filtered list always need its own useState?', '', ['Yes', 'No, it can be derived from items and query', 'Only when there are three items'], 1, 'If current inputs determine the result, derive it rather than synchronize another copy.'), q('cleanup', 'What should an interval effect return?', 'useEffect(() => { const id = setInterval(tick, 1000); ... }, [])', ['Nothing', 'A function calling clearInterval(id)', 'The numeric interval id'], 1, 'React calls the cleanup function when the effect is replaced or the component unmounts.')],
    repIds: ['derive-task-summary', 'frontend-visible-items', 'frontend-directory'], related: ['testing', 'frontend'],
  },
  {
    id: 'testing', title: 'Tests, boundaries, and evidence', summary: 'Turn requirements into checks without confusing passed cases with complete proof.', prerequisites: ['values'],
    objectives: ['Choose checks from requirements rather than implementation details.', 'Cover boundaries, failures, and input preservation.', 'Explain the limits of behavioral tests.'],
    sections: [
      { title: 'Arrange, act, assert', body: 'Set up a meaningful input, call the behavior under test, and compare the observable result with the contract. A test that merely repeats the implementation can repeat its bug. Use independently reasoned expectations.' },
      { title: 'Boundary coverage', body: 'Include empty input, exact limits, just-outside limits, duplicates, conflicting states, and malformed input where the contract allows them. A regression case should expose the original defect. Verify unchanged input when mutation is forbidden.' },
      { title: 'What passing means', body: 'Passing checks means the code matched the cases run. It does not establish all possible behavior, readability, accessibility, or understanding. Use manual review and unfamiliar transfer tasks for evidence those checks cannot provide.' },
    ],
    example: '// Contract: strictly above 5\ncountAbove([4, 5, 6], 5) // expected 1\ncountAbove([], 5) // expected 0\n// The equality boundary catches >= instead of >.',
    walkthrough: ['Choose one value below, one equal, and one above.', 'Reason about the expected result before executing.', 'Include empty input to check initialization.', 'Add a regression case when a defect is discovered.'],
    mistakes: ['Testing only the example.', 'Deriving expected output with the same algorithm being tested.', 'Treating passed checks as proof of understanding.'],
    questions: [q('test-boundary', 'Which case separates > from >=?', 'Count values strictly above 5.', ['[6]', '[5]', '[]'], 1, 'Equality is the distinguishing boundary.'), q('test-proof', 'What do passed checks establish?', '', ['Complete mastery', 'Correct results for the checked cases', 'A universally optimal solution'], 1, 'Tests provide specific evidence; broader claims need other assessment methods.')],
    repIds: ['debug-cart-total', 'backend-validate-user', 'debug-page-offset'], related: ['debugging', 'validation'],
  },
  {
    id: 'databases', title: 'Data modeling and database boundaries', summary: 'Model records, query a predictable result, and keep related changes atomic.', prerequisites: ['validation', 'http'],
    objectives: ['Explain primary keys and relationships.', 'Use parameterized queries for data values.', 'Distinguish filtering, ordering, and transactions.'],
    sections: [
      { title: 'Records and identity', body: 'A table stores records with defined fields. A primary key identifies one record; a foreign key connects it to another. Use stable IDs rather than display names as identity. Constraints such as unique and not null enforce rules even when application code misses them.' },
      { title: 'Query contracts', body: 'Use WHERE to filter and ORDER BY for a defined order. Do not assume rows come back in insertion order without ordering. Parameterized queries pass values separately from SQL syntax; string interpolation can turn input into executable query text.' },
      { title: 'Transactions', body: 'A transaction groups related writes so they commit together or roll back. For example, importing a profile should not leave half its attempts saved. An index can improve a frequent lookup but costs storage and write work; measure the actual query.' },
    ],
    example: 'SELECT id, title FROM tickets\nWHERE status = ?\nORDER BY id\nLIMIT ? OFFSET ?\n// Pass status, size, and offset as separate parameter values.',
    walkthrough: ['The filter limits which records qualify.', 'Ordering makes the returned sequence explicit.', 'Limit and offset select a page.', 'Parameters supply values without becoming SQL syntax.'],
    mistakes: ['Building SQL by concatenating user text.', 'Assuming a result order without ORDER BY.', 'Saving related writes separately when partial success is invalid.'],
    questions: [q('sql-values', 'How should user input be passed to SQL?', '', ['String concatenation', 'Query parameters', 'Removing all spaces'], 1, 'Parameters keep data values separate from SQL syntax.'), q('transaction', 'What protects an import from partial writes?', '', ['A transaction', 'A longer file name', 'Sorting the JSON keys'], 0, 'A transaction provides all-or-nothing commit behavior for related writes.')],
    repIds: ['backend-ticket-handler', 'project-ticket-api', 'validate-page-query'], related: ['http', 'testing'],
  },
  ...practicalSkills,
]
export const skillById = (id: string) => skills.find(skill => skill.id === id)
export const skillsForRep = (id: string) => skills.filter(skill => skill.repIds.includes(id))
export const contentVersion = 4

// Discovery categories only; these do not change skill identity or learner evidence.
export const knowledgeGroups: { id: string; title: string; skillIds: string[] }[] = [
  { id: 'language', title: 'Language & problem solving', skillIds: ['values', 'arrays', 'text', 'lookup', 'stacks', 'complexity'] },
  { id: 'frontend', title: 'Frontend', skillIds: ['frontend', 'react'] },
  { id: 'backend', title: 'Backend & data', skillIds: ['validation', 'http', 'databases'] },
  { id: 'async', title: 'Async & runtime', skillIds: ['async', 'closures', 'reference-identity', 'event-loop', 'debouncing', 'throttling', 'request-ownership'] },
  { id: 'resources', title: 'Patterns & resources', skillIds: ['singleton', 'events', 'dependency-injection', 'resource-ownership', 'websockets', 'live-transports'] },
  { id: 'reliability', title: 'Reliability & testing', skillIds: ['debugging', 'testing', 'caching', 'retries', 'idempotency', 'optimistic-updates'] },
]
