import { InfoNote, ListGroup, PageHeader } from './Layout'
import { Button } from './Button'
import { Icon } from './Icon'
import { StepIndicator } from './StepIndicator'
import { ProjectListLoading } from './LoadingStates'
import { learningPageTitles } from './learning-pages'
import type { HubTab } from './learning-pages'
import { revealElement } from './ui-motion'
import { Input, NumberInput, Select, Textarea } from './Input'
import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { skills, skillById, knowledgeGroups } from './knowledge'
import { lessonDepth } from './lesson-depth'
import { capstones, diagnosticRepIds, recurringReviews, rubrics, skillEvidence, weeklyPlan } from './fluency'
import type { FluencyState, Judgment, LearningNote, SelfReview } from './fluency'
import type { PortableRecord } from './portability'
import { paths } from './path'
import { reps } from './rep'
import { useSessionPreference } from './useSessionPreference'
const BrowserProjects = lazy(() => import('./BrowserProjects').then(module => ({ default: module.BrowserProjects })).catch(() => ({ default: () => <section role="alert"><p>Browser projects could not load. Reload to try again; your saved work will be kept.</p><Button onClick={() => window.location.reload()}>Reload projects</Button></section> })))
export type { HubTab } from './learning-pages'
type Props = { journalTabs?: ReactNode; tab: HubTab; setTab: (tab: HubTab) => void; state: FluencyState; update: (next: FluencyState) => boolean; error: string; history: PortableRecord[]; openRep: (id: string) => void; reviewRep: (id: string) => void; skillId: string; onSkill: (id: string) => void; onQuickLessons: () => void; candidates: { repId: string; reason: string; mode?: string }[] }
const labels: Record<Judgment,string> = { 'not-yet': 'Not yet', 'with-help': 'With help', independent: 'Independently' }
const defaultReview = (): SelfReview => ({ understanding: 'not-yet', approach: 'not-yet', implementation: 'not-yet', explanation: 'not-yet', evidence: '', updatedAt: new Date().toISOString() })
function Lesson({ skillId, state, update, openRep, onSkill, history }: Omit<Props, 'error' | 'reviewRep' | 'candidates' | 'tab' | 'setTab' | 'onQuickLessons'>) {
  const skill = skillById(skillId) ?? skills[0]
  const article = useRef<HTMLElement>(null)
  const [section, setSection] = useSessionPreference<string>(`lesson-section:${skill.id}`, 'read')
  const [reviewOpen, setReviewOpen] = useState(false)
  useEffect(() => { revealElement(article.current?.querySelector(`#lesson-${section}`) ?? null) }, [section, skill.id])
  function revealLesson(next: string) {
    setSection(next)
    if (next === 'review') setReviewOpen(true)
  }
  const [choices,setChoices]=useState<Record<string,number>>({})
  const [responses,setResponses]=useState<Record<string,string>>({})
  const depth = lessonDepth[skill.id]
  const evidence=skillEvidence(skill.id,history,state)
  const review=state.reviews[skill.id]??defaultReview()
  function saveReview(key: keyof SelfReview, value: string) { update({...state,reviews:{...state.reviews,[skill.id]:{...review,[key]:value,updatedAt:new Date().toISOString()}}}) }
  return <article ref={article} className="knowledge-article"><div className="hub-heading"><div><h2>{skill.title}</h2><p>{skill.summary}</p></div><Button type="button" aria-pressed={state.bookmarks.includes(skill.id)} onClick={()=>update({...state,bookmarks:state.bookmarks.includes(skill.id)?state.bookmarks.filter(id=>id!==skill.id):[...state.bookmarks,skill.id]})}>{state.bookmarks.includes(skill.id)?'Bookmarked':'Bookmark'}</Button></div>
    <nav className="lesson-navigation" aria-label="Lesson sections"><StepIndicator active={section} />{['read', 'predict', 'practise', 'review'].map(id => <Button key={id} aria-current={section === id ? 'location' : undefined} onClick={() => revealLesson(id)}>{({ read: 'Read', predict: 'Predict', practise: 'Practise', review: 'Review' } as Record<string, string>)[id]}</Button>)}</nav>
    <div id="lesson-read" hidden={section !== 'read'} tabIndex={-1}>
    {skill.prerequisites.length>0&&<div className="prerequisite-links"><strong>Helpful foundations</strong>{skill.prerequisites.map(id=><Button type="button" key={id} onClick={()=>onSkill(id)}>{skillById(id)?.title}</Button>)}<p>These are suggestions. You can practise any skill at any time.</p></div>}
    <section><h3>What you will learn</h3><ul>{skill.objectives.map(o=><li key={o}>{o}</li>)}</ul></section>
    {skill.sections.map(section=><section key={section.title}><h3>{section.title}</h3><p>{section.body}</p></section>)}
    <section><h3>A worked example</h3><pre><code>{skill.example}</code></pre><ol>{skill.walkthrough.map(step=><li key={step}>{step}</li>)}</ol></section>
    {depth && <section><h3>{depth.title}</h3><pre><code>{depth.code}</code></pre><p>{depth.reasoning}</p><h4>Reason it through</h4><p>{depth.challenge}</p><p>Write a prediction and a reason before revealing the discussion. This is self-review, separate from checked lesson answers.</p><details><summary>Compare your reasoning</summary><p>{depth.answer}</p></details></section>}
    <section><h3>Common mistakes</h3><ul>{skill.mistakes.map(m=><li key={m}>{m}</li>)}</ul></section>
    </div>
    <section id="lesson-predict" hidden={section !== 'predict'} tabIndex={-1}><h3>Predict, then check</h3><p>These short checks exercise recognition and tracing. They do not establish independent coding fluency.</p>{skill.questions.map(question=>{
      const id=`${skill.id}:${question.id}`;const answer=state.answers[id];const choice=choices[id]??answer?.choice;const response=responses[id]??answer?.response??''
      return <fieldset className="lesson-question" key={id}><legend>{question.prompt}</legend>{question.code&&<pre><code>{question.code}</code></pre>}{question.completion?<label>Missing code<Input type="text" value={response} maxLength={300} onChange={e=>setResponses({...responses,[id]:e.target.value})} spellCheck={false}/></label>:question.options.map((option,i)=><label key={option}><Input type="radio" name={id} checked={choice===i} onChange={()=>setChoices({...choices,[id]:i})}/>{option}</label>)}<Button variant="primary" type="button" disabled={question.completion?!response.trim():choice===undefined} onClick={()=>update({...state,answers:{...state.answers,[id]:{choice:question.completion?question.answer:choice!,correct:question.completion?response.trim()===question.options[question.answer]:choice===question.answer,answeredAt:new Date().toISOString(),...(question.completion?{response}: {})}}})}>Check prediction</Button>{answer&&<p className="lesson-feedback feedback-note" data-state={answer.correct ? 'success' : 'error'} role="status"><Icon name={answer.correct ? 'check' : 'alert'} /><strong>{answer.correct?'Correct prediction.':'Revisit this idea.'}</strong> {question.explanation} <span>Last checked {new Date(answer.answeredAt).toLocaleDateString()}.</span></p>}</fieldset>
    })}</section>
    <section id="lesson-practise" hidden={section !== 'practise'} tabIndex={-1}><h3>Apply the skill</h3><div className="rep-links">{skill.repIds.map(id=><Button type="button" key={id} onClick={()=>openRep(id)}>{reps.find(r=>r.id===id)?.title}</Button>)}</div></section>
    <div id="lesson-review" hidden={section !== 'review'} tabIndex={-1}><details className="lesson-review-details" open={reviewOpen} onToggle={event => setReviewOpen(event.currentTarget.open)}><summary>Your evidence and self-assessment</summary>
    <section className="skill-evidence"><h3>Your evidence</h3><p>{evidence.lessonCorrect} of {evidence.lessonTotal} latest predictions correct. {evidence.attempts.length} completed coding attempts; {evidence.independent.length} without revealed hints.</p><p>{evidence.retained?`Delayed independent recall recorded ${new Date(evidence.retained.completedAt).toLocaleDateString()}.`:'No delayed independent recall recorded for this skill.'} Code checks and predictions do not assess your written reasoning.</p>{evidence.attempts.length>0&&<details><summary>Inspect the attempts</summary><ul>{evidence.attempts.slice(0,10).map(a=><li key={a.id}>{reps.find(r=>r.id===a.repId)?.title} · {new Date(a.completedAt).toLocaleDateString()} · {a.hintCount} hints</li>)}</ul></details>}</section>
    <section><h3>Assess yourself</h3><InfoNote><p>Use the criteria and name the attempt or example supporting your judgment. These are your assessments, separate from checked behavior.</p></InfoNote><div className="rubric-grid">{(Object.keys(rubrics) as (keyof typeof rubrics)[]).map(dimension=><fieldset key={dimension}><legend>{dimension}</legend><ul>{rubrics[dimension].map(point=><li key={point}>{point}</li>)}</ul><label>Your judgment<Select value={review[dimension]} onChange={e=>saveReview(dimension,e.target.value)}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></label></fieldset>)}</div><label htmlFor="lesson-evidence">Evidence and what to improve</label><Textarea id="lesson-evidence" value={review.evidence} maxLength={20_000} rows={4} onChange={e=>saveReview('evidence',e.target.value)} placeholder="Name the attempt, explain your evidence, and identify a next step."/>{state.reviews[skill.id]&&<p className="utility-note">Self-review updated {new Date(review.updatedAt).toLocaleString()}.</p>}</section>
    </details></div>
    <section hidden={section !== 'read'}><h3>Related knowledge</h3><div className="rep-links">{skill.related.map(id=><Button type="button" key={id} onClick={()=>onSkill(id)}>{skillById(id)?.title}</Button>)}</div></section>
  </article>
}
function Notebook({state,update}: Pick<Props,'state'|'update'>) {
  const [query,setQuery]=useState('');const [editing,setEditingState]=useState<LearningNote|null>(state.noteDraft??null)
  function setEditing(next: LearningNote | null) { setEditingState(next); update({...state,noteDraft:next??undefined}) };const [confirm,setConfirm]=useState('')
  const [message,setMessage]=useState('')
  const visible=state.notes.filter(note=>`${note.title} ${note.body} ${note.kind} ${skillById(note.skillId)?.title??''}`.toLowerCase().includes(query.toLowerCase()))
  function newNote(){setEditing({id:crypto.randomUUID(),title:'',body:'',skillId:'',repId:'',kind:'note',updatedAt:new Date().toISOString()});setMessage('')}
  return <><div className="hub-heading"><div><p>Keep recurring mistakes, questions, and ideas next to the skill or attempt they concern.</p></div><Button variant="primary" type="button" onClick={newNote}>New entry</Button></div><label>Search notes<Input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a concept or mistake"/></label>
    {editing&&<form className="hub-panel" onSubmit={e=>{e.preventDefault();if(!editing.title.trim())return;if(update({...state,noteDraft:undefined,notes:[{...editing,title:editing.title.trim(),updatedAt:new Date().toISOString()},...state.notes.filter(n=>n.id!==editing.id)]})){setEditingState(null);setMessage('Entry saved.')}else setMessage('Entry could not be saved. Keep this form open and retry.')}}><h3>{state.notes.some(n=>n.id===editing.id)?'Edit entry':'New entry'}</h3><label>Title<Input required maxLength={120} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><div className="hub-form-row"><label>Kind<Select value={editing.kind} onChange={e=>setEditing({...editing,kind:e.target.value as LearningNote['kind']})}><option value="note">Note</option><option value="mistake">Mistake</option><option value="question">Question</option></Select></label><label>Skill<Select value={editing.skillId} onChange={e=>setEditing({...editing,skillId:e.target.value})}><option value="">General</option>{skills.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</Select></label><label>Exercise<Select value={editing.repId} onChange={e=>setEditing({...editing,repId:e.target.value})}><option value="">No exercise</option>{reps.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</Select></label></div><label>What you learned<Textarea maxLength={20_000} rows={7} value={editing.body} onChange={e=>setEditing({...editing,body:e.target.value})}/></label><div className="hub-actions"><Button variant="primary" type="submit">Save entry</Button><Button type="button" onClick={()=>setEditing(null)}>Cancel</Button></div></form>}
    {message&&<p className="hub-message feedback-note" data-state={message === 'Entry saved.' ? 'success' : 'error'} role="status"><Icon name={message === 'Entry saved.' ? 'check' : 'alert'} />{message}</p>}<div className="hub-cards">{visible.map(note=><article className="hub-panel" key={note.id}><span className="home-label">{note.kind}</span><h3>{note.title}</h3><p className="note-body">{note.body}</p><p className="utility-note">{skillById(note.skillId)?.title} {note.repId&&` · ${reps.find(r=>r.id===note.repId)?.title}`} · {new Date(note.updatedAt).toLocaleDateString()}</p><div className="hub-actions"><Button type="button" onClick={()=>setEditing(note)}>Edit</Button>{confirm===note.id?<><Button variant="danger" type="button" onClick={()=>{update({...state,notes:state.notes.filter(n=>n.id!==note.id)});setConfirm('')}}>Confirm delete</Button><Button type="button" onClick={()=>setConfirm('')}>Keep entry</Button></>:<Button type="button" onClick={()=>setConfirm(note.id)}>Delete…</Button>}</div></article>)}</div>{!visible.length&&<div className="hub-empty"><span className="home-label">{query?'No matches':'Your notebook'}</span><h3>{query?'Try another search.':'Make your next attempt useful.'}</h3><p>{query?'No matching entries.':'Your notebook is empty. Save an idea or mistake after your next attempt.'}</p>{!query&&<Button variant="primary" onClick={newNote}>Write your first entry</Button>}</div>}</>
}
export function LearningHub(props: Props) {
  useEffect(() => {
    // Restore the page heading after a focused loading placeholder is replaced.
    if (document.activeElement === document.body) document.querySelector<HTMLElement>('.learning-hub h1')?.focus({ preventScroll: true })
  }, [])
  const {state,update,history,openRep,reviewRep,onSkill,skillId}=props
  const { tab, setTab } = props
  const lessonRef = useRef<HTMLDivElement>(null)
  function selectSkill(id: string) {
    onSkill(id)
    if (matchMedia('(max-width: 900px)').matches) setIndexOpen('closed')
    requestAnimationFrame(() => {
      const lesson = lessonRef.current
      lesson?.scrollIntoView({ block: 'start', behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' })
      lesson?.focus({ preventScroll: true })
    })
  }
  const [query,setQuery]=useSessionPreference<string>('knowledge-query','')
  const [bookmarkFilter,setBookmarkFilter]=useSessionPreference<'all' | 'bookmarked'>('knowledge-bookmarks','all')
  const bookmarked=bookmarkFilter==='bookmarked'
  const [topic,setTopic]=useSessionPreference<string>('knowledge-topic','')
  const [now,setNow]=useState(Date.now)
  const [minutes,setMinutes]=useState(30)
  const [roundRep, setRoundRep] = useSessionPreference<string>('interview-focus', 'interview-frontend')
  useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[])
  const matching=skills.filter(s=>(!bookmarked||state.bookmarks.includes(s.id))&&`${s.title} ${s.summary} ${s.sections.map(x=>x.body).join(' ')} ${s.objectives.join(' ')}`.toLowerCase().includes(query.toLowerCase()))
  const groups=knowledgeGroups.filter(group=>!topic||group.id===topic).map(group=>({...group,lessons:matching.filter(skill=>group.skillIds.includes(skill.id))})).filter(group=>group.lessons.length)
  const reviews=recurringReviews(history,now)
  const currentRound=state.rounds.find(r=>!r.endedAt)
  const diagnostic=diagnosticRepIds.map(id=>{const attempts=history.filter(r=>r.repId===id&&state.diagnosticStartedAt&&Date.parse(r.completedAt)>=Date.parse(state.diagnosticStartedAt));return {rep:reps.find(r=>r.id===id)!,attempt:attempts[0]}})
  const missing=diagnostic.find(d=>!d.attempt||d.attempt.hintCount)
  const [indexOpen, setIndexOpen] = useSessionPreference<'open' | 'closed'>('lesson-index', matchMedia('(min-width: 901px)').matches ? 'open' : 'closed')
  return <main className="learning-hub"><PageHeader eyebrow={tab === 'notebook' ? 'Journal' : undefined} title={learningPageTitles[tab].title} description={learningPageTitles[tab].description} actions={tab === 'notebook' ? props.journalTabs : undefined} />{props.error&&<p role="alert">{props.error}</p>}
    {tab==='knowledge'&&<div className="knowledge-layout"><details className="knowledge-browser" open={indexOpen === 'open'} onToggle={event => setIndexOpen(event.currentTarget.open ? 'open' : 'closed')}><summary>Browse lessons<span aria-live="polite">{groups.reduce((count, group) => count + group.lessons.length, 0)} available</span></summary><aside className="knowledge-index"><div className="knowledge-controls">
      <label>Search knowledge<Input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try arrays or promises"/></label>
      <label>Topic<Select value={topic} onChange={e=>setTopic(e.target.value)}><option value="">All topics</option>{knowledgeGroups.map(group=><option key={group.id} value={group.id}>{group.title}</option>)}</Select></label>
      <label className="check-label"><Input type="checkbox" checked={bookmarked} onChange={e=>setBookmarkFilter(e.target.checked?'bookmarked':'all')}/>Bookmarks only</label>
      <Button variant="text" onClick={props.onQuickLessons}>Quick lessons</Button>
      </div><nav aria-label="Skills">{groups.map(group=><details className="knowledge-group" key={group.id} open={Boolean(query.trim())||Boolean(topic)||bookmarked||group.skillIds.includes(skillId)}>
        <summary>{group.title}<span>{group.lessons.length}</span></summary>
        <div className="knowledge-topic-list">{group.lessons.map(skill=><Button type="button" key={skill.id} aria-current={skillId===skill.id?'page':undefined} onClick={()=>selectSkill(skill.id)}><strong>{skill.title}</strong><Icon name="arrow" /></Button>)}</div>
      </details>)}</nav>
      {!groups.length&&<p>No matching knowledge. Try another term or clear filters.</p>}
      {(query||topic||bookmarked)&&<Button variant="text" onClick={()=>{setQuery('');setTopic('');setBookmarkFilter('all')}}>Clear knowledge filters</Button>}
    </aside></details><div ref={lessonRef} tabIndex={-1} className="knowledge-reading"><Lesson key={skillId} skillId={skillId} state={state} update={update} openRep={openRep} onSkill={selectSkill} history={history}/></div></div>}
    {tab==='assessment'&&<><section className="hub-panel"><h2>A short self-assessment</h2><InfoNote><p>Optional: solve four short tasks before using hints. Your code checks show behavior; review your reasoning separately. This is a snapshot of these skills, not an overall coding score.</p></InfoNote><Button variant="primary" type="button" onClick={()=>update({...state,diagnosticStartedAt:new Date().toISOString()})}>{state.diagnosticStartedAt?'Start a new assessment':'Start assessment'}</Button>{state.diagnosticStartedAt&&<><p>Started {new Date(state.diagnosticStartedAt).toLocaleString()}. Earlier attempts remain in History.</p><ol className="milestone-list">{diagnostic.map(({rep,attempt})=><li key={rep.id}><div><strong>{rep.title}</strong><p>{attempt?`${attempt.hintCount?'Completed with help':'Completed without hints'} · ${new Date(attempt.completedAt).toLocaleDateString()}`:'No completed attempt since this assessment started.'}</p></div><Button variant="text" type="button" onClick={()=>reviewRep(rep.id)}>Try from a fresh start</Button></li>)}</ol><p><strong>Suggested focus:</strong> {missing?`${missing.rep.category}: ${missing.attempt?'try a related problem without hints.':'start here to gather evidence.'}`:'You completed these tasks without revealed hints. Try a practical project and later recall to gather broader evidence.'}</p></>}</section><div className="hub-evidence">{knowledgeGroups.map(group=><ListGroup key={group.id} title={group.title} count={group.skillIds.length}>{skills.filter(skill=>group.skillIds.includes(skill.id)).map(skill=>{const evidence=skillEvidence(skill.id,history,state);return <li key={skill.id}><details className="hub-panel evidence-card"><summary><h3>{skill.title}</h3><span className="evidence-stage">{evidence.retained?'Recall recorded':evidence.independent.length?'Checked without hints':evidence.attempts.length?'Practising':'Gather evidence'}</span></summary><div className="evidence-card-body"><p>{evidence.attempts.length} checked completions · {evidence.independent.length} without hints · {evidence.lessonCorrect}/{evidence.lessonTotal} latest predictions</p><p>{evidence.retained?'Delayed recall recorded':'Delayed recall not established'}{evidence.selfReview?` · Self-reviewed ${new Date(evidence.selfReview.updatedAt).toLocaleDateString()}`:' · No self-review yet'}</p>{evidence.selfReview&&<dl className="compact-rubric">{(Object.keys(rubrics) as (keyof typeof rubrics)[]).map(key=><div key={key}><dt>{key}</dt><dd>{labels[evidence.selfReview![key]]}</dd></div>)}</dl>}<Button variant="text" type="button" onClick={()=>{onSkill(skill.id);setTab('knowledge')}}>Inspect evidence and assess</Button></div></details></li>})}</ListGroup>)}</div></>}
    {tab==='plan'&&<><section className="hub-panel"><h2>A manageable practice week</h2><InfoNote><p>Choose a goal and time budget. Suggestions mix due reviews, saved work, and your target path. Time is a budget, not an estimate of mastery.</p></InfoNote><div className="hub-form-row"><label>Goal path<Select value={state.goal.pathId} onChange={e=>update({...state,goal:{...state.goal,pathId:e.target.value}})}>{paths.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</Select></label><label>Minutes per session<NumberInput min={5} max={120} value={state.goal.minutes} onValueChange={value=>update({...state,goal:{...state.goal,minutes:value}})}/></label></div><fieldset className="day-picker"><legend>Practice days</legend>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day,i)=><label key={day}><Input type="checkbox" checked={state.goal.days.includes(i)} onChange={()=>update({...state,goal:{...state.goal,days:state.goal.days.includes(i)?state.goal.days.filter(d=>d!==i):[...state.goal.days,i]}})}/>{day}</label>)}</fieldset><ol className="milestone-list">{weeklyPlan(state.goal,props.candidates).map(session=><li key={session.date.toISOString()}><div><strong>{session.date.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})} · {session.minutes} minutes</strong><p>{session.action?`${reps.find(r=>r.id===session.action!.repId)?.title}: ${session.action.reason}`:'Use this session for your notebook or a knowledge lesson.'}</p></div>{session.action&&<Button variant="text" type="button" onClick={()=>session.action!.mode==='review'||session.action!.mode==='retry'?reviewRep(session.action!.repId):openRep(session.action!.repId)}>Open practice</Button>}</li>)}</ol>{!state.goal.days.length&&<p>Select at least one day to make a plan. Nothing is scheduled until you do.</p>}</section><section className="hub-panel"><h2>Keep skills available</h2><InfoNote><p>After first delayed recall, additional reviews rotate through different applications. Successful independent scheduled recalls extend the interval; difficult or hinted recalls shorten it. These intervals are starting rules to validate with learners.</p></InfoNote>{reviews.length?<ul className="milestone-list">{reviews.map(review=><li key={review.skillId}><div><strong>{review.title}</strong><p>{review.due?'Ready now':`Next review ${new Date(review.dueAt).toLocaleDateString()}`} · {review.successes} further independent recalls</p><p>{review.reason}</p></div><Button variant="text" type="button" disabled={!review.due} onClick={()=>reviewRep(review.repId)}>Fresh review</Button></li>)}</ul>:<p>Complete a guided, independent, and delayed recall journey to begin recurring reviews.</p>}</section></>}
    {tab==='notebook'&&<Notebook state={state} update={update}/>}
    {tab==='projects'&&<><Suspense fallback={<ProjectListLoading />}><BrowserProjects openRep={openRep} recordReflection={(title, body) => {
      const note: LearningNote = { id: crypto.randomUUID(), title, body, skillId: 'frontend', repId: '', kind: 'note', updatedAt: new Date().toISOString() }
      if (update({ ...state, notes: [note, ...state.notes] })) setTab('notebook')
    }} /></Suspense><h2>In-app integration projects</h2>{capstones.map(project=><details key={project.id} className="hub-panel project-overview"><summary><h2>{project.title}</h2><p>{project.brief}</p><span>{project.milestones.length} milestones</span></summary><ol className="milestone-list">{project.milestones.map(m=>{const completed=history.find(a=>a.repId===m.repId);return <li key={m.repId}><div><strong>{m.title}</strong><p>{completed?`Completed ${new Date(completed.completedAt).toLocaleDateString()} with ${completed.hintCount} hint(s).`:'Not completed yet.'}</p></div><Button variant="text" type="button" onClick={()=>openRep(m.repId)}>Open milestone</Button></li>})}</ol><details className="project-review"><summary>Final self-review</summary><ul>{project.review.map(point=><li key={point}>{point}</li>)}</ul><Button variant="text" type="button" onClick={()=>{setTab('notebook')}}>Record a project reflection</Button></details></details>)}</>}
    {tab==='interview'&&<><section className="hub-panel"><h2>Optional timed practice</h2><InfoNote><p>Clarify, plan, implement, explain, and review. Timing is recorded separately from checks and your self-assessment. The timer does not submit or erase your work.</p></InfoNote>{!currentRound?<><label>Round length in minutes<NumberInput min={5} max={120} value={minutes} onValueChange={setMinutes}/></label><label htmlFor="interview-focus">Interview focus</label><Select id="interview-focus" value={roundRep} onChange={event => setRoundRep(event.target.value)}><option value="interview-frontend">Frontend</option><option value="interview-backend">Backend</option></Select><div className="hub-actions"><Button variant="primary" type="button" disabled={!Number.isInteger(minutes)||minutes<5||minutes>120} onClick={()=>{update({...state,rounds:[{id:crypto.randomUUID(),repId:roundRep,minutes,startedAt:new Date().toISOString(),clarification:'',debrief:''},...state.rounds]});reviewRep(roundRep)}}>Start round</Button></div></>:<><p><strong>{reps.find(r=>r.id===currentRound.repId)?.title}</strong> · {Math.max(0,Math.ceil((Date.parse(currentRound.startedAt)+currentRound.minutes*60_000-now)/60_000))} minutes remaining</p><label>Clarifications and assumptions<Textarea rows={3} maxLength={20_000} value={currentRound.clarification} onChange={e=>update({...state,rounds:state.rounds.map(r=>r.id===currentRound.id?{...r,clarification:e.target.value}:r)})}/></label><div className="hub-actions"><Button variant="primary" type="button" onClick={()=>openRep(currentRound.repId)}>Continue coding</Button><Button type="button" onClick={()=>update({...state,rounds:state.rounds.map(r=>r.id===currentRound.id?{...r,endedAt:new Date().toISOString()}:r)})}>End round and review</Button></div></>}</section>{state.rounds.filter(r=>r.endedAt).map(round=><section className="hub-panel" key={round.id}><h3>{reps.find(r=>r.id===round.repId)?.title}</h3><p>{new Date(round.startedAt).toLocaleString()} · {Math.ceil((Date.parse(round.endedAt!)-Date.parse(round.startedAt))/60_000)} minutes elapsed · {round.minutes}-minute budget</p><p>Clarifications: {round.clarification||'None recorded.'}</p><label>Debrief: approach, implementation, explanation, and next focus<Textarea rows={4} maxLength={20_000} value={round.debrief} onChange={e=>update({...state,rounds:state.rounds.map(r=>r.id===round.id?{...r,debrief:e.target.value}:r)})}/></label><p className="utility-note">Review checked attempts in History and record skill judgments in Self-assessment. Elapsed time is not a correctness score.</p></section>)}</>}
  </main>
}
