import type { Rep } from './rep'

const tickets = [
  { id: 't1', title: 'Login issue', status: 'open' },
  { id: 't2', title: 'Invoice copy', status: 'closed' },
  { id: 't3', title: 'Login on mobile', status: 'open' },
]
const ok = (items: unknown[], total: number, page = 1, size = 2) => ({ status: 200, body: { items, total, page, size } })
const badQuery = { status: 400, body: { error: 'INVALID_QUERY' } }
const directory = [{ name: 'Ada' }, { name: 'Bo' }, { name: 'Adam' }]

export const richReps: Rep[] = [
  {
    id: 'debug-cart-total', title: 'Debug a checkout total', category: 'Real-world debugging', format: 'debug',
    context: 'Bug report: removing a sold-out item changes the total, and a quantity of two is charged as one. The checkout team needs the total in whole cents.',
    prompt: 'Repair cartTotal. Include only available items, multiply each price in cents by quantity, then subtract the discount once. The final total cannot be below zero. Do not change input objects.',
    example: { input: 'cartTotal([{ priceCents: 250, quantity: 2, available: true }], 100)', output: '400' },
    note: 'Prices, quantities, and discount are nonnegative integers. A quantity of zero contributes nothing. An empty cart returns zero.',
    vocabulary: [{ term: 'Regression', meaning: 'a previously working behavior that breaks after a change' }, { term: 'Cents', meaning: 'whole units one hundredth of a currency unit' }],
    planPrompt: 'Trace the reported quantity bug. Which line causes it? Name a regression case for unavailable items and one for the discount.',
    starter: 'type CartItem = { priceCents: number; quantity: number; available: boolean }\n\nfunction cartTotal(items: CartItem[], discountCents: number): number {\n  let total = 0\n  for (const item of items) {\n    if (item.available) total += item.priceCents\n    else total -= item.priceCents\n    total -= discountCents\n  }\n  return total\n}\n',
    functionName: 'cartTotal', preserveInput: true,
    hints: ['Trace two available items and notice how often the discount is subtracted.', 'An unavailable item contributes zero; an available item contributes price times quantity.', 'Subtract the discount after calculating the subtotal, then clamp the result to zero.'],
    checks: [
      { name: 'Charges every unit in the example', input: [[{ priceCents: 250, quantity: 2, available: true }], 100], expected: 400 },
      { name: 'Applies the discount only once', input: [[{ priceCents: 200, quantity: 1, available: true }, { priceCents: 300, quantity: 1, available: true }], 100], expected: 400 },
      { name: 'Ignores sold-out items', input: [[{ priceCents: 500, quantity: 3, available: false }, { priceCents: 100, quantity: 1, available: true }], 0], expected: 100 },
      { name: 'Clamps a discount larger than the subtotal', input: [[{ priceCents: 100, quantity: 1, available: true }], 150], expected: 0 },
      { name: 'Handles an empty cart', input: [[], 100], expected: 0 },
      { name: 'Ignores zero quantity', input: [[{ priceCents: 250, quantity: 0, available: true }], 0], expected: 0 },
      { name: 'Allows free items', input: [[{ priceCents: 0, quantity: 3, available: true }], 0], expected: 0 },
    ],
  },
  {
    id: 'frontend-directory', title: 'Build an interactive directory', category: 'Frontend implementation', format: 'frontend',
    context: 'A small team directory needs clear request states and a search field. Build the DOM in the preview, then verify interactions against the same code.',
    prompt: 'Implement mountDirectory(root, state). Loading takes priority over error; show Loading… with no controls. A nonempty error shows Could not load people. and a Retry button that calls state.retry once per click. Otherwise show a labelled Search people input and a list of names. Filter names on every input event using a trimmed, case-insensitive substring query, preserving original labels and order. With no matches, show No people found.',
    example: { input: "ready people: Ada, Bo, Adam; search: ' AD '", output: 'Ada, Adam' },
    note: 'Use data-testid="message" for the message, data-testid="search" for the search input, data-testid="retry" for the retry button, and data-testid="person" on each list item. Use label text Search people with a matching input id. Render names as text, not HTML. Checks cover behavior; use the manual review checklist for layout and keyboard access.',
    acceptanceCriteria: ['Loading, error, empty, and ready states can be selected in the preview.', 'Search updates without a submit button and can be cleared.', 'Retry is reachable by keyboard and calls the supplied callback.', 'Use a real label, input, list, list items, and button; keep text readable and focus visible.'],
    vocabulary: [{ term: 'DOM', meaning: 'the elements and text that make up a browser page' }, { term: 'Event listener', meaning: 'a function called when a person interacts with an element' }],
    planPrompt: 'Choose the state precedence, then plan how an input event updates the list. How will you insert a name safely and keep the original data unchanged?',
    starter: 'type DirectoryState = { loading: boolean; error: string | null; people: { name: string }[]; retry: () => void }\n\nfunction mountDirectory(root: HTMLElement, state: DirectoryState): void {\n  // Build elements with document.createElement and attach them to root.\n  // The preview and checks supply state.retry.\n  root.replaceChildren()\n}\n',
    functionName: 'mountDirectory', preserveInput: true,
    hints: ['Return early for loading, then error; build the search and list only in the loaded state.', 'Build a renderList helper and call it initially and on the input event. Read input.value inside that listener.', 'Normalize only the query and comparison text. Use textContent for the original names, and wire Retry with addEventListener.'],
    checks: [
      { name: 'Loading wins over error and existing data', input: [{ loading: true, error: 'Offline', people: directory }], expected: { message: 'Loading…', people: [], search: false, retry: false, retryCalls: 0 } },
      { name: 'Error displays a working retry button', input: [{ loading: false, error: 'Offline', people: directory }, { clickRetry: true }], expected: { message: 'Could not load people.', people: [], search: false, retry: true, retryCalls: 1 } },
      { name: 'Loaded empty data has search and an empty message', input: [{ loading: false, error: null, people: [] }], expected: { message: 'No people found.', people: [], search: true, retry: false, retryCalls: 0 } },
      { name: 'Ready state shows original names in order', input: [{ loading: false, error: null, people: directory }], expected: { message: '', people: ['Ada', 'Bo', 'Adam'], search: true, retry: false, retryCalls: 0 } },
      { name: 'Typing filters a normalized query', input: [{ loading: false, error: null, people: directory }, { queries: [' AD '] }], expected: { message: '', people: ['Ada', 'Adam'], search: true, retry: false, retryCalls: 0 } },
      { name: 'No search matches show the empty message', input: [{ loading: false, error: null, people: directory }, { queries: ['zzz'] }], expected: { message: 'No people found.', people: [], search: true, retry: false, retryCalls: 0 } },
      { name: 'Clearing search restores the full list', input: [{ loading: false, error: null, people: directory }, { queries: ['zzz', ''] }], expected: { message: '', people: ['Ada', 'Bo', 'Adam'], search: true, retry: false, retryCalls: 0 } },
      { name: 'An empty error string means ready', input: [{ loading: false, error: '', people: directory }], expected: { message: '', people: ['Ada', 'Bo', 'Adam'], search: true, retry: false, retryCalls: 0 } },
      { name: 'Names containing markup remain text', input: [{ loading: false, error: null, people: [{ name: '<b>Ada</b>' }] }], expected: { message: '', people: ['<b>Ada</b>'], search: true, retry: false, retryCalls: 0 } },
    ],
  },
  {
    id: 'read-batch-labels', title: 'Trace a batch label pipeline', category: 'Code reading', format: 'read',
    context: 'Before changing a teammate’s importer, predict what it keeps and in what order. Write your trace in the plan before running checks.',
    prompt: 'Read collectLabels in the starter. Complete predictLabels with the output you predict for each named case: repeat = [" Ada ", "Bo", "Ada"], empty = [], blank = [" ", "", "Bo"], case = ["Ada", "ada", "Ada"]. Return each predicted list. Keep collectLabels unchanged and explain how trim, Set, and the loop affect the result.',
    example: { input: "predictLabels('repeat')", output: "['Ada', 'Bo']" },
    note: 'This is a prediction exercise, not a request to repair collectLabels. You may write each predicted array directly. Checks verify predictions; your written trace is self-reviewed.',
    vocabulary: [{ term: 'Pipeline', meaning: 'a sequence of steps that transforms data' }, { term: 'Trace', meaning: 'follow values through code one step at a time' }],
    planPrompt: 'For repeat, record the trimmed label and current Set after each iteration. Predict blank and case before coding your answers.',
    starter: 'function collectLabels(input: string[]): string[] {\n  const seen = new Set<string>()\n  const output: string[] = []\n  for (const raw of input) {\n    const label = raw.trim()\n    if (label !== "" && !seen.has(label)) {\n      seen.add(label)\n      output.push(label)\n    }\n  }\n  return output\n}\n\nfunction predictLabels(caseName: "repeat" | "empty" | "blank" | "case"): string[] {\n  // Write the output you predict for each named input in the brief.\n  return []\n}\n',
    functionName: 'predictLabels',
    hints: ['Follow raw and label separately: trimming changes the value before the Set lookup.', 'Empty trimmed labels are skipped; the Set compares uppercase and lowercase separately.', 'The output array preserves the first occurrence of each accepted trimmed label.'],
    checks: [
      { name: 'Predicts trimming and deduplication', input: ['repeat'], expected: ['Ada', 'Bo'] },
      { name: 'Predicts empty input', input: ['empty'], expected: [] },
      { name: 'Predicts blank-label removal', input: ['blank'], expected: ['Bo'] },
      { name: 'Predicts case-sensitive comparison', input: ['case'], expected: ['Ada', 'ada'] },
    ],
  },
  {
    id: 'backend-ticket-handler', title: 'Implement a ticket list handler', category: 'Backend implementation', format: 'backend',
    context: 'A support dashboard needs the GET /tickets contract. Implement its request handler as a pure function; the worker supplies request objects and data without starting a network server.',
    prompt: 'Implement handleTickets(request, tickets). Only GET is supported; other methods return 405 with {error:"METHOD_NOT_ALLOWED"}. Query must be a non-null, non-array object. Optional status is open or closed, search is a string, page is an integer at least 1, and size is an integer from 1 through 3. Defaults: page 1, size 2, empty search, no status filter. Invalid query returns 400 with {error:"INVALID_QUERY"}. Filter status and a trimmed, case-insensitive title substring, then page in original order. Return 200 with {items,total,page,size}; total is the filtered count before paging.',
    example: { input: 'GET /tickets?status=open&page=2&size=1 (the supplied three-ticket dataset)', output: '{status:200,body:{items:[{id:"t3",title:"Login on mobile",status:"open"}],total:2,page:2,size:1}}' },
    note: 'Method validation takes priority over query validation. Unknown query fields are ignored. Undefined optional fields use defaults; null is invalid. Do not coerce strings to numbers or mutate tickets. This rep models parsed request data, not raw URL parsing.',
    vocabulary: [{ term: 'Handler', meaning: 'a function that receives a request and produces a response' }, { term: 'Status code', meaning: 'a number describing whether a request succeeded or failed' }],
    planPrompt: 'Restate the 405 and 400 boundaries. In what order must filtering, counting, and pagination happen? Which values need runtime checks?',
    starter: 'type Ticket = { id: string; title: string; status: "open" | "closed" }\ntype TicketRequest = { method: string; query: unknown }\ntype TicketResponse = { status: number; body: { error: string } | { items: Ticket[]; total: number; page: number; size: number } }\n\nfunction handleTickets(request: TicketRequest, tickets: Ticket[]): TicketResponse {\n  // Validate the method and query, filter, count, then page.\n  return { status: 200, body: { items: [], total: 0, page: 1, size: 2 } }\n}\n',
    functionName: 'handleTickets', preserveInput: true,
    hints: ['Reject unsupported methods first, then reject unsafe query shapes before reading fields.', 'Validate optional fields without coercion. Build the filtered array before calculating total.', 'Calculate the page offset from validated page and size, then slice a new array.'],
    checks: [
      { name: 'Uses defaults and counts before paging', input: [{ method: 'GET', query: {} }, tickets], expected: ok(tickets.slice(0, 2), 3) },
      { name: 'Returns the second filtered page', input: [{ method: 'GET', query: { status: 'open', page: 2, size: 1 } }, tickets], expected: ok([tickets[2]], 2, 2, 1) },
      { name: 'Combines status and normalized search', input: [{ method: 'GET', query: { status: 'open', search: ' MOBILE ' } }, tickets], expected: ok([tickets[2]], 1) },
      { name: 'Counts matches even beyond the last page', input: [{ method: 'GET', query: { page: 9 } }, tickets], expected: ok([], 3, 9) },
      { name: 'Returns a loaded empty result', input: [{ method: 'GET', query: {} }, []], expected: ok([], 0) },
      { name: 'Rejects unsupported method before invalid query', input: [{ method: 'POST', query: null }, tickets], expected: { status: 405, body: { error: 'METHOD_NOT_ALLOWED' } } },
      ...([
        ['null query', null], ['array query', []], ['string query', 'page=1'],
        ['unknown status', { status: 'pending' }], ['non-string search', { search: 7 }],
        ['page below one', { page: 0 }], ['fractional page', { page: 1.5 }], ['string page', { page: '2' }],
        ['size below one', { size: 0 }], ['size above three', { size: 4 }], ['fractional size', { size: 1.5 }],
        ['null size', { size: null }], ['null page', { page: null }], ['null search', { search: null }], ['null status', { status: null }],
      ] as [string, unknown][]).map(([name, query]) => ({ name: `Rejects ${name}`, input: [{ method: 'GET', query }, tickets], expected: badQuery })),
      { name: 'Filters closed tickets', input: [{ method: 'GET', query: { status: 'closed' } }, tickets], expected: ok([tickets[1]], 1) },
      { name: 'Uses defaults for undefined optional fields', input: [{ method: 'GET', query: { page: undefined, size: undefined, search: undefined, status: undefined } }, tickets], expected: ok(tickets.slice(0, 2), 3) },
      { name: 'Treats a whitespace search as empty', input: [{ method: 'GET', query: { search: '  ' } }, tickets], expected: ok(tickets.slice(0, 2), 3) },
      { name: 'Allows maximum page size and ignored fields', input: [{ method: 'GET', query: { size: 3, ignored: true } }, tickets], expected: ok(tickets, 3, 1, 3) },
      { name: 'Returns no matching titles', input: [{ method: 'GET', query: { search: 'missing' } }, tickets], expected: ok([], 0) },
    ],
  },
  {
    id: 'refactor-stock-summary', title: 'Refactor a stock summary', category: 'Refactoring', format: 'refactor',
    context: 'This stock report works, but its repeated loops and unclear names make changes risky. Improve its structure while preserving the full contract.',
    prompt: 'Refactor stockSummary. For available products, return their IDs in input order, total available units, and total stock value in cents (priceCents times units). Do not change inputs. Keep the same response shape and behavior. Use the existing checks to protect the refactor, then explain why your names and structure are easier to follow.',
    example: { input: 'stockSummary([{id:"a",available:true,units:2,priceCents:150}])', output: '{ids:["a"],units:2,valueCents:300}' },
    note: 'Units and prices are nonnegative integers. Available products with zero units still appear in ids. Duplicate IDs remain duplicated. Tests assess behavior; the quality of your refactoring is self-reviewed.',
    vocabulary: [{ term: 'Refactoring', meaning: 'improving code structure while preserving its behavior' }, { term: 'Accumulator', meaning: 'a value that collects a result during a loop' }],
    planPrompt: 'Identify duplication and unclear names before editing. Which checks protect zero units, duplicate IDs, and input preservation?',
    starter: 'type Product = { id: string; available: boolean; units: number; priceCents: number }\n\nfunction stockSummary(p: Product[]): { ids: string[]; units: number; valueCents: number } {\n  const a: string[] = []\n  let b = 0\n  let c = 0\n  for (let i = 0; i < p.length; i++) {\n    if (p[i].available === true) a.push(p[i].id)\n  }\n  for (let i = 0; i < p.length; i++) {\n    if (p[i].available === true) b += p[i].units\n  }\n  for (let i = 0; i < p.length; i++) {\n    if (p[i].available === true) c += p[i].units * p[i].priceCents\n  }\n  return { ids: a, units: b, valueCents: c }\n}\n',
    functionName: 'stockSummary', preserveInput: true,
    hints: ['Name each accumulator by the value it represents.', 'All three loops use the same condition; consider a single pass.', 'For each available product, append its ID and update units and valueCents together.'],
    checks: [
      { name: 'Preserves the example', input: [[{ id: 'a', available: true, units: 2, priceCents: 150 }]], expected: { ids: ['a'], units: 2, valueCents: 300 } },
      { name: 'Excludes unavailable stock', input: [[{ id: 'a', available: false, units: 10, priceCents: 150 }]], expected: { ids: [], units: 0, valueCents: 0 } },
      { name: 'Preserves available IDs with zero units', input: [[{ id: 'a', available: true, units: 0, priceCents: 150 }]], expected: { ids: ['a'], units: 0, valueCents: 0 } },
      { name: 'Preserves order and duplicate IDs', input: [[{ id: 'z', available: true, units: 1, priceCents: 20 }, { id: 'a', available: false, units: 9, priceCents: 9 }, { id: 'z', available: true, units: 3, priceCents: 10 }]], expected: { ids: ['z', 'z'], units: 4, valueCents: 50 } },
      { name: 'Handles an empty report', input: [[]], expected: { ids: [], units: 0, valueCents: 0 } },
      { name: 'Includes free stock units', input: [[{ id: 'gift', available: true, units: 5, priceCents: 0 }]], expected: { ids: ['gift'], units: 5, valueCents: 0 } },
    ],
  },
]
